### ISSUE TITLE
DB Lambda Functions which return record objects instead of JSON

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/features#100]
The current lambda is JSON in and JSON out. However, in many use case, developer want records in and records out; or more often, JSON in and records out. Currently, there is no suggested way or tools to facilitate that.

Proposal:
* Support another type of Cloud Functions (let's say `DB Lambda Functions`) which is a decorator in py-skygear, or something like `.DBop()` in js.
* In `DB Lambda Functions`, we support return record object or array of record objects from skygear query. In the case of Python, would have a util for sqlalchemy result.
* In Client side, the returned record objects can be used directly just like other record objects.
* In Client side, it might be affected by #112 Ideally we should support both Records and custom subclass.

# API Design

## Scenario

This is like the number one painpoint of Skygear usage for Oursky Developers

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
@carmenlau I want to ask if this feature have already covered part of the problem at #4 ? My understanding is partly, as this issue convert JSON <=> Skygear Records. However if users opt to use SQL / ORM, the ORM won't output the right JSON that we can convert to Skygear Records here.

**Comment by carmenlau** [comment]
@chpapa #4 is not covered in this feature. In this feature, if user returns record from lambda, user will be able to get the result as record object in client SDK. We can further do #4, and the full picture will be user can use their own SQL/ORM, convert the result to record object and return in lambda. #100 will help convert the result to record in client SDK.

**Comment by carmenlau** [comment]
Development done and available in master. Will close this issue after release

**Comment by chpapa** [comment]
Closing all v1 only issues
