### ISSUE TITLE
React Native Chat Demo project

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#109]
- Check and verify if current JS SDK is working with reactive native
- Create issues for JS SDK
- Add reactive native demo project

**Comment by chpapa** [comment]
May I suggest to make it a Chat Demo Project? The reasons are:

1. Business Team are focusing on Chat, so create a Chat Demo Project could help us verify (again) how good are the Chat SDK. And any improvement needed.

2. We might be able to have a UIKit for React Native?

**Comment by chpapa** [comment]
@carmenlau So if it is no longer on progress let me remove it from Milestone 4.1?

**Comment by carmenlau** [comment]
Ok, thanks @chpapa
