### ISSUE TITLE
Support disable a user

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/features#116]
# Description

There are cases to temporary disable a user. For example, violation of the term of use; awaiting settle of a payment, etc.

Currently, a developer can do two things to achieve the goal.
1. Change the password of the user. (Usually add a `!` in front of the password has to make it invalid)
2. Mark the user as disabled at `user` record.

When a user needs to recover the account, just use the reset password function provided by the [forgot password](https://github.com/SkygearIO/forgot_password) plugin.

# CMS Design

TODO

## CMS Features

- A button to disable a user temporarily
  - After clicking the button, display a text area for setup the disabled message when the user tries to log in.
- A button to enable the user back

# API Design

**Remove this section if the feature have no API**

## Scenario

**Put list of Scenario how developers will use this API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
Duplicated with #50
