### ISSUE TITLE
Skygear Chat Usability Improvement

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#118]
I am opening this relatively special feature issue as a collective for usability problem we have realized during the development of UIKit, demo project, and early users.

Please jot down all issues you face and put issue numbers next to the point form below if issues were created. Problems there might not have good or trivial solutions.

* [x] `createConversation` with `distinctByPartcipants` set to true, could return an error when participants exists. Is it possible to return the conversation object of the conflicted conversation / ID along with the error? (Or have a `getConversations` with participants list?)
* [x] ~~When building a conversation list, it is very common for UI need to display username, profile etc. It would be very helpful to eager load user record along with getConversations.~~ Should go to #64 
* [x] createConversation / createDirectConversation only takes userID, should take user object too?

**Comment by chpapa** [comment]
I found that createConversation and DirectConversation only take `userID` and `participantsID` as parameters. I think it makes sense to support User Record object directly too (in lots of case it will look better in syntax). So I added an item above. @carmenlau @howawong

**Comment by carmenlau** [comment]
Now the createConversation / createDirectConversation allow user object or id in js, for static type language we used ids for avoid confusion. The usability problem is addressed.
