### ISSUE TITLE
Push Notification Support for Chat

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#123]
# Description

We should support most common Push Notification setting out-of-the-box.

Requirements:
* Have the following built-in push notification for chat:
  * Send push to User B when User A send message to User B, content is the message
  * Send push to all Users in a group when User A send to the group, content is the message
  * Send push to User B when User A start typing to User B (Snapchat Style)
* Work with UIKit, 
  * When push notification is pressed, it should jump to UIKit Conversation of the message
  * Support Quick Action like Reply in iOS and Android
* Able to customize or disable entirely.

Approach:
* Approach A: Like Parse or Layer, have some sort of Class in Client side for developers to configure the Push
* Approach B: What if we just have a template Cloud Functions repo, for users to clone (or support it from skycli)? The default code should do everything of the above, with in-line comments to tell users how they can customize it. It requires very good and readable function names too.
* Approach C: Extension of Approach B, but we have those hooks and template in Developer Portal. So we have an inline javascript editor in Portal, like "after message sent", with a template functions there to listen to the hooks.

My initial preference is Approach B, but I'm open to it. I'm also not sure how easy would be for Approach B to support UIKit, as the template would need to support both with/without UIKit.

If we go with Approach B, I also suggest besides the standard after_save hook, maybe we need to have new hook for pubsub for typing indicator, or even some specialized hooks for chat: https://github.com/SkygearIO/chat/issues/158

# Portal Design

**Remove this section if the feature have no Portal**

## Portal Features

**Put Portal Feature List here**

# API Design

**Remove this section if the feature have no API**

## Scenario

**Put list of Scenario how developers will use this API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues: https://github.com/SkygearIO/chat/issues/158
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by carmenlau** [comment]
The event hooks are done, what we left is implementation the generic payload for ios and android.

https://github.com/SkygearIO/features/blob/master/features/123-chat-push-notification/api.md
