### ISSUE TITLE
Remove "type/" from record ID in SDKs

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#126]
# Description

Currently, record ID consist of this format: `type/uuid` e.g. (`user/1FD43CF9-934E-4CD9-9463-4A45A1F3F9F0`). Since some SDK/Plugin API expects ID to have no type information, this confuses user as to what Record ID is.

This proposal suggest we use only `uuid` for Record ID instead of `type/uuid`.

For Objective-C/Swift, the `SKYRecordID` will be replaced with string type. For APIs that require `SKYRecordID`, they will be replaced with `String type, String ID` parameters.

# API Design

Before:

```
Record ID is in this format: user/1FD43CF9-934E-4CD9-9463-4A45A1F3F9F0

Record Class:
            RecordID recordID (maybe called `id` in JS)

RecordID Class:
            String recordType
            String recordName

Database Class:
            fetch(RecordID recordID)
            fetchMany(RecordID[] recordIDs)
            delete(RecordID recordID)
            deleteMany(RecordID[] recordIDs)
            save(Record[] records)
```

After:

```
Record ID is in this format: 1FD43CF9-934E-4CD9-9463-4A45A1F3F9F0

Record Class:
            String recordType
            String recordID (maybe called `id` in JS)

Database Class:
            fetch(String recordType, String recordID)
            fetchMany(String recordType, String[] recordIDs)
            delete(String recordType, String recordID)
            deleteMany(String recordType, String[] recordIDs)
            save(Record[] records)
```

# Scenario

* This will mostly benefit new learner/user of the SDK

# Open Questions

* Do we need to change the API backward compatible?

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by limouren** [comment]
We would have to consider the effect on Reference as well. e.g. currently Reference constructor has the following signature in JS SDK:

```
new Reference(Record | string)
```

Where string is expected to be in the format or `${recordType}/${recordName}`.

**Comment by rickmak** [comment]
When we considering how to modify it, we may want to take a look at how other using the type/typeless ID.

For example people are expecting there is no type: https://github.com/SkygearIO/skygear-SDK-JS/issues/350
People is using the type: https://github.com/SkygearIO/chat/blob/master/doc/pubsub.md
No type in the whole code base: https://github.com/SkygearIO/forgot_password

**Comment by chpapa** [comment]
I was reading the [draft proposal](https://gist.github.com/carmenlau/e610aebc3e88995e357c4fb8f9c5e316) by @carmenlau

It seems if we remove "type/" from ID, a lot of API which accept ID without type information will need to have API interface change, unless we scarify the performance or add complexity of having an ID to type mapping.

I think what's important is consistent. Have we considered, instead of removing `type/`, what about if we make sure all ID have `type/` and we don’t accept any record ID not start with `type/`?

It seems easier as we can minimise the breaking changes on API?
