### ISSUE TITLE
Support for Security Audit Feature

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#140]
# Description

This issue is the specification to support the security audit of client [redacted].

The suggestion is to provide a plugin which enables the following features:
1. Require minimum password length
1. Enforce password complexity
1. Exclude password keywords
1. Audit trails

Optional:
1. Enforce password expiry

# API Design

## Require minimum password length
Configure via envvar:

`USER_AUDIT_PW_MIN_LENGTH=0` (0 is disabled)

When enabled, when sign up / change password, password length shorter than requirement will return an error with:
* Password minimal length
* The length

## Enforce password complexity
Configure via envvar:

`USER_AUDIT_PW_UPPERCASE_REQUIRED=false`
`USER_AUDIT_PW_LOWERCASE_REQUIRED=false`
`USER_AUDIT_PW_NUMERALS_REQUIRED=false`
`USER_AUDIT_PW_SYMBOLS_REQUIRED=false`
`USER_AUDIT_PW_MIN_GUESSABLE_LEVEL=0` (0-4)

If any of the requirement does not fit when sign up / change password, an error will be returned with:
* Password Complexity Problem
* The reason (Uppercase Required / Lowercase Required / Numerals Required / Symbols Required / Too Simple)

For password guessable level, it should be using: https://github.com/dropbox/zxcvbn

## Exclude password keywords
Configure via envvar:
`USER_AUDIT_PW_EXCLUDED_KEYWORDS=` (default is empty)
`USER_AUDIT_PW_EXCLUDED_FIELDS=` (default is empty)

For keywords, it should be a comma seperated string, for example:
`USER_AUDIT_PW_EXCLUDED_KEYWORDS=user,admin`

meant all password cannot contains keywords of `user` or `admin`, in whatever cases.

For fields, it should be a comma seperated string for field name, for example:
`USER_AUDIT_PW_EXCLUDED_FIELDS=firstname,lastname`

It meant all password cannot contains the words appear in the user's firstname and lastname field. (If the field name is invalid, it will continue correctly)

If any of the requirement does not fit when sign up / change password, an error will be returned with:
* Password contains dictionary keywords

## Audit trails
Configure via envvar:

`USER_AUDIT_ENABLED=false`

If it is true, a table will be created with all audits logs of the following:

* Login success
  * Timestamp
  * IP Address of the Login origin
  * Username
* Login failure
  * Timestamp
  * IP Address of the Login origin
  * Username
* Logout
  * Timestamp
  * IP Address of the Login origin
  * Username
* User Created
  * Timestamp
  * IP Address of the Login origin (or portal username and IP address)
  * Username
* Password Reset
  * Timestamp
  * IP Address of the Login origin (or portal username and IP address)
  * Username
* User Deleted
  * Timestamp
  * IP Address of the Login origin (or portal username and IP address)
  * Username
* User Role changed
  * Timestamp
  * IP Address of the Login origin (or portal username and IP address)
  * Username
  * Old Roles
  * New Roles
* Setting Changed
  * Timestamp
  * Environment variable name
  * Old Envvar Value
  * New Envvar Value

# Portal Design

## Portal Features

[TBD]

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by carmenlau** [comment]
# Password validation

For password validation part, we tends to put it in skygear server instead of adding password validation hook. Talked with @louischan-oursky, they also need password history to prevent the reuse of passwords. Did some research on the other services, the spec already cover most of the case and good enough to put it into the core server.

What we are missing here:

## Password history 
Configure via envvar:

`USER_AUDIT_PW_HISTORY_SIZE=0`
- When enabled, server will get the last `x` password history from db, user cannot reuse those password.

`USER_AUDIT_PW_HISTORY_DAYS=0` 
- When enabled, server will get password history in last x days, user cannot reuse those password.

Need adding new db table for password history, bcrypt password will be stored.

## Enforce password expiry
Configure via envvar:

`USER_AUDIT_PW_EXPIRY_DAYS=0`

- When enabled, all require auth handlers will return 401 when pw expired (Done by preprocessor in skygear server)
- Login will fail when password expired
- User can change password through server handler which require old and new password
- If user forgot his password, he will need to reset the password through forgot password plugin

# Audit trails

We will do in it in skygear-server and setup hooks that they needs. User can enable it by environment variable. No cloud code is needed. 

FYI: https://github.com/sirupsen/logrus

**Comment by louischan-oursky** [comment]
As per offline discussion, we decided to keep minimum password history as oppose to keeping all password history regardless of configuration.

- The server must keep password history if either `USER_AUDIT_PW_HISTORY_SIZE` or `USER_AUDIT_PW_HISTORY_DAYS` is non-zero.
- The server must not keep password history if both `USER_AUDIT_PW_HISTORY_SIZE` and `USER_AUDIT_PW_HISTORY_DAYS` is non-zero.
- The server should only keep minimum password history to fulfil the requirement of `USER_AUDIT_PW_HISTORY_SIZE` and `USER_AUDIT_PW_HISTORY_DAYS`

**Comment by rickmak** [comment]
After https://github.com/SkygearIO/skygear-server/commit/37291e0bec641391f18e6520dc1c49a7a7da204c

The feature on skygear-server is complete. But SDK are not able to handle the sigin/change password error due to password complexity.

**Comment by chpapa** [comment]
> The feature on skygear-server is complete. But SDK are not able to handle the sigin/change password error due to password complexity.

@carmenlau So we will need a spec for this? Draft in milestone 4.1? Probably like a set of error specifically about password complexity / history in signup / change password API at client side?

**Comment by cheungpat** [comment]
i think this can be closed?

**Comment by chpapa** [comment]
Agreed I think it is duplicated with #154 and was completed.
