### ISSUE TITLE
Common payload for iOS and Android push notification

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#141]
# Description

1. Improve the register and unregister flow
1. Common payload for api to send push notification to apns and gcm

#### Existing (Assume register device require user login):

- Skygear server handler
    - register (require auth) - create device
    - unregister - delete device

- iOS SDK
    -  register - if user is not logged in, will call server register device and server exception
    -  user login - no related handling
    -  user logout - call unregister device

- android SDK
    -  register - if user is not logged in, will not call server register device
    -  user login - call register device
    -  user logout - call unregister device

#### Problem

- In iOS, after user has not updated the notification relation. If user request token before login, the token cannot send to server. Need to wait until user open the app next time.

_*Stage 1 quick fix*_

Update iOS SDK like android

_*Stage 2 improvement*_

Register token should not login require

- Skygear server
    - register (not require auth) - create device
    - unregister - delete device
    - link user with device (require auth) - link user with registered device id
    - unlink user with device - unlink user with registered device id

- iOS and android SDK
   - login and logout should call link and unlink respectively

### Common payload for api to send push notification to apns and gcm

WIP

**Comment by chpapa** [comment]
close all v1-only issues
