### ISSUE TITLE
Removal of record subscription

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/features#142]
# Description

I would like to propose that we remove the record subscription feature and related APIs, because:

* it is rarely used
* it introduces a concept of “internal pubsub” which is problematic
  * no one understand why there is an internal pubsub anymore
  * SDK keeps two connections to the server, with the internal pubsub rarely used
  * complicates cloud deployment because the `/_/pubsub` routes to a different service in the case of multiple instance skygear apps
* the code is not maintained for a long time and the developer who wrote that part has left the core team
* have related unresolved panics https://github.com/SkygearIO/skygear-server/issues/136
* the performance characteristics for a Public DB is not clear
  * there are potentially huge number of records in a Public DB, and subscribing for changes in that DB is something we have no guarantee for
* this is likely to interfere with https://github.com/SkygearIO/features/issues/141 which aims to remove the requirement for a user account from device registration, record subscription requires device and record subscription requires a user

# Portal Design/Features

There is no changes to the portal.

# API Design

API related to record subscription are to be removed across all SDKs

## Scenario

While record subscription has been with skygear server for a long time, there is a lack of use case for its use. Developer is likely to send custom push notification and/or pubsub via cloud code instead of relying record subscription.

# Open Questions

The most likely question is probably “if there is no complaints regarding subscription, why not keep it?” I would like to argue that we do not have the necessary resource to maintain this part of the system, and removing this part allows us to focus on other components of Skygear.

# Related Issues

- Server Issues
  - https://github.com/SkygearIO/skygear-server/issues/136
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
Sounds weird to me...

* it is rarely used
  * how we know it is relatively rarely used? I know at least one paid user using it...
* on internal pubsub
  * is that something we should refactor if that is problematic? Say share the same pubsub connections with the pubsub module.
* the code is not maintained for a long time and the developer who wrote that part has left the core team
  * I guess in most large software project 80% of the code are were never touch for years...

For performance, I guess it is a real issue that might need some attentions in future.
