### ISSUE TITLE
Improve the suggested way of skygear-SDK-JS usage in cloud deploy

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/features#160]
# Description

Current common usage of cloud

```
const { Record, ErrorCodes, Query } = require('skygear');
const skygearCloud = require('skygear/cloud');
const { getContainer, SkygearError } = skygearCloud;
```

Importing two skygear here is a bit weird. And it is proved easy to have error in issue: 
https://github.com/SkygearIO/skygear-SDK-JS/pull/360
https://github.com/SkygearIO/chat-SDK-JS/issues/78
https://github.com/SkygearIO/skygear-SDK-JS/pull/354

# Portal Design

**Remove this section if the feature have no Portal**

## Portal Features

**Put Portal Feature List here**

# API Design

The suggested way should be as following

```
const skygear = require('skygear/cloud');
const { Record, ErrorCodes, Query, getContainer, SkygearError } = skygear;
```

## Scenario

**Put list of Scenario how developers will use this API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by cheungpat** [comment]
Hoping this will also consider https://github.com/SkygearIO/skygear-SDK-JS/issues/423
