### ISSUE TITLE
Include Skygear Chat plugins in the release builds

### ISSUE THREAD

**Issue by david90** [SkygearIO/features#177]
# Description

It's hard to deploy Chat server with custom deployment. 
In the conversation with other developers, it might be good to provide extra builds /docker images for Chat-enabled servers.

Example:
-  skygear-server-darwin-amd64.tar.gz
-  skygear-server-with-chat-darwin-amd64.tar.gz

(etc.)

## Scenario

Developers can deploy a Chat-enabled server to their own container / machine with the provided build. Without setting up py-skygear and installing the Chart plugin.

# Open Questions

- This is a priority question, do we want to make custom deployment that easy so users can opt for their own deployment?
- Is it the best way handling Chat server deployment?
- What to do if we want to extend this to other plugins (or support JS plugins)?
- Is there any foreseeable maintenance difficulties?

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
I think it would be easier for us to maintain, if we simply force and provide instructions on how to deploy with docker-compose for everything. So we don't need to maintain multiple documents / build for a different way to deploy.
