### ISSUE TITLE
Image Resize API

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#191]
# Description

A very common use case for Skygear Cloud Functions is to resize/crop images; It will definitely save up developer a lot of time if Skygear has it built-in.

Suggested feature:

- [ ] * Optimize images [for SEO purpose](https://developers.google.com/speed/docs/insights/OptimizeImages)
- [x] * Retrieve image in a different format (jpg, png, webp)
- [ ] * Encode images in different parameters:
  - [x]   * JPEG: Quality, Progressive 
  - [x]   * PNG: Downsize to 8-bits
- [ ] * Resize & Cropping: 
  - [x]   * width, height
  - [ ]   * top, right, left, bottom (default is resize only, specified to crop)
- [x]   * resize / crop behavior
  - [ ] * Content-aware Resize
  - [ ]   * Use this? https://github.com/esimov/caire
- [ ]   * Support the flag of `width`, `height`, `perc`, `square`, `scale`, `blur`, `sobel`, `face`
  - [ ] * Flip / Roate, bgcolor
  - [ ] * Blur
  - [ ] * Affine Transformation / Interpolator

Reference:
* https://rsz.io
* https://kraken.io/docs/image-resizing
* https://www.contentful.com/developers/docs/references/images-api/#/reference/resizing-&-cropping/specify-focus-area-for-resizing

There are several form of APIs for our consideration:
* As URL parameters (like rsz.io or [aliyun](https://www.alibabacloud.com/help/doc-detail/44688.htm))
* As API

URL parameters have advantages that it can be used easily on Web and Mobile, but technically it meant we need to serve and cache the images from our server instead of taking advantage of S3. Maybe a trade off is we provide a server/plugins instance at open sources version, and for skygear.io we use CloudFront to cache a origin from skygear server instance.

What use case are APIs better?

# API Design

**Remove this section if the feature have no API**

## Scenario

**Put list of Scenario how developers will use this API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by rickmak** [comment]
As previously discuss with @b123400 @louischan-oursky , I think what is handy is JIT resize image on the asset upload. No need to write cloud code and pre-defined of image size.

refs: https://www.alibabacloud.com/help/doc-detail/44688.htm

**Comment by louischan-oursky** [comment]
We can also take from some insights here
https://developers.google.com/speed/docs/insights/OptimizeImages

Optimizing the image can benefit SEO.

**Comment by chpapa** [comment]
Thanks! @louischan-oursky included that on the feature issue.

@rickmak Included that on feature issue too. But would JIT resize on upload make things complicated when some new resolution are needed?

**Comment by rickmak** [comment]
Sorry, I mean the JIT is download time. i.e. you do not need to specify the images size needed on upload time. You specify the size want at the retrieve time via query strings.

**Comment by louischan-oursky** [comment]
Remaining features are now being tracked in https://github.com/SkygearIO/features/issues/393
