### ISSUE TITLE
Identify have a record updated after create

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#199]
# Description

Reported by @hidden-dimensions, when he is using login with custom token, he want to know if the user record changed after signup. He want to do so by comparing the _created_at and _updated_at time for he expect the time should be the same if it is a new record. But there are slightly different between 2 values. 

## Discussion

Should we provide another way for user to determine if the record is new?

**Comment by chpapa** [comment]
I assumed it is obsoleted.
