### ISSUE TITLE
List login sessions and invalidate all other / individual session from SDK

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#202]
# Description

It is a common requirement to manage login sessions / invalidate all other or individual session. 

## Scenario

1. Have a setting page which lists all login user session with the following data. And able to log each session out, or have a button to log ALL other session out.
    * Last location used
    * Last time used (or Active now)
    * Last IP addresses
    * Device type(?) / Browser Type
1. After some operation, such as validate a new phone number, need to invalidate all sessions.

# API Design

Something like these?

* Client side SDK (JS, iOS, Android):
  * `skygear.auth.listSessions()` => return an array of dicts.
  * `skygear.auth.invalidateSession(sessionToken)`
  * `sykgear.auth.invalidateAllSessions(exceptCurrentSession=true)`
* The above API should be usable at Cloud Functions too

# Open Questions

* Maybe it doesn’t make sense to make JWT stateful just for invalidate sessions? Could consider alternatives such as using a short auth token + long refresh token with blacklist on refresh token / login. Or other idea (search online?)
* For login sessions history, shall we use redis or postgresql?

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by carmenlau** [comment]
Would like to bring this up, we had a short discussion within the team. For the session management, we may also want to support refresh token. If so, we may need to have it before the first launch as this should be a breaking change. Can further discuss in the product meeting.

**Comment by louischan-oursky** [comment]
The client sdk should have a callback mechanism to handle token expiration error.
