### ISSUE TITLE
Change password hook

### ISSUE THREAD

**Issue by yipsang** [SkygearIO/features#206]
# Description

The developer wants to perform certain actions after the end user changes their password.

## Scenario

Client required an email to be sent after the password is changed by end-user.

**Comment by chpapa** [comment]
@carmenlau I remember it was discussed before but I forgot the content... do you have any idea?

**Comment by carmenlau** [comment]
@chpapa We discussed about this, last time we need to validate the password so we come up with password policy and password history. We thought that can cover most of the use cases. This time we need to send email after user reset password which is not covered. We can further observe if this use case common.

**Comment by chpapa** [comment]
@carmenlau so actually would it be easier if we just have an event hook after user password change for Cloud Functions?

**Comment by chpapa** [comment]
Close as it should be reflect in #285
