### ISSUE TITLE
Improve Skygear APIs' consistency across all the SDKs

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/features#207]
# Description

Currently, APIs across all SDKs are not unified, which confuses users who need to use more than 1 SDK, and it is harder to fix such inconsistency the longer we wait.

Below is a comparison of the APIs across all the SDKs:

https://docs.google.com/spreadsheets/d/1ZzWivcjd0nzmESZFfdOtaOIQzBWF_L56UA_b2BX-09A/edit?usp=drive_web&ouid=114348132664197091849

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by Steven-Chan** [comment]
https://docs.google.com/spreadsheets/d/1Vit4L5z2fQrDKOrZjIpFWdSdMBhhBBBs5eocxKVbtHQ/edit#gid=0

This spreadsheet list out my suggestions on the change of the API, and is mostly based on the previous spreadsheet, i.e. comparison of the APIs across all the SDKs.

The list is still WIP, feel free to leave comments.

**Comment by chpapa** [comment]
Leaving this issue open as a reminder for NEXT to have more consistent SDKs amongst platforms.
