### ISSUE TITLE
Support email verification after sign up

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#22]
# Description

Handle the use case of User Profile have an email field, and users need to verify by emails before using certain functions.

# Portal Design

## Portal Features

* Portal Setting (Under `User Auth` > `Email Verification`)
  * Setting (Enable, Sender, From, Reply To)
  * Verify Email Template (sent when email verification requested)
  * Verify Confirmation HTML Template (display the HTML when the confirmation link in **Verify Email** is clicked)
  * Email Address Change Notification Email Template (optional, sent to old email address when email change)
  * Each Email Template / HTML Template in Portal have a "Try" button for a preview.
  * Each email template should have the following fields:
    * From Email Address
    * Subject
    * Reply to
    * Content
    * Redirect URL (only applicable for emails)
    * URL Lifetime (only applicable for HTML templates)
  * Content are expected to be an HTML / plain text editor with placeholder variable. The list of placeholder variable should include all the fields under the User table, and something like `[[url]]` to include the link to confirmation result page.

## UX Design
**Put (link to) Portal Design here**

# API Design

## Scenario

* Simple blogging apps that require email verification to post new blog post
  * Send a verification email when non-verified users logged in and tried to post a new blog post
  * Display a page say "You need your email to be verified before a new post" if user's email was not verified.
  * After the user clicks on the link of verified email, it should show a page say "Verified email", and users can click elsewhere to continue what they do.

## Sample Code

When user click on an action that require email verification:
```
if !currentUser.email_verified
  skygear.userUtils.sendEmailVerfication('actionX')
```

The above code will send an email, and the verification links after clicked, will comes with actionX as the parameter. `actionX` will pass as a string as query string to the redirected URL after the verification link is clicked, or ignored if users supply an HTML template.

## API Design

**Put Design and Specification here with links**

* Call `sendEmailVerification(currentLink)` from client side
* `User.email_verified` return `true` or `false`

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
I have renamed the issue from "upon signup" to "after signup", and added a parameter for `sendEmailVerfication` which will pass as query parameter to the redirected URL after email verification link was clicked, so that developers can use it to implement "resume some actions" after email is verified.

This is useful as these days a lot of apps does NOT require email verification upon sign up, but only when users want to do something in the apps. So the verification email might not send upon sign up, and usability-wise the developer would like to let the users continue what they wanted to do before the verification happens.

**Comment by arsewizz** [comment]
Hi, is this feature available?

**Comment by chpapa** [comment]
> Hi, is this feature available?

Not yet sorry :(

**Comment by chpapa** [comment]
Code completed, guides and portal will be done in #200
