### ISSUE TITLE
Remove non-atomic record save

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/features#221]
# Description

The current default behaviour of multiple record save is inatmoic, i.e. when saving more than one record in one record save request, some may succeed while some may fail.

This introduces complexity to both server side and client side, which I think is not worthy because in most application, saving records atomically is a more rational solution.

If developers need the behaviour of saving records inatomically, they can simply fire separate record save calls.

```js
// no more partial success
try {
  const results = await skygear.publicDB.save([recordA, recordB, recordC]);
  console.log(results);
} catch (e) {
  console.log(e);
}

// saving inatomically
records.forEach(async function (record) {
  try {
    const result = await skygear.publicDB.save(record);
    console.log(result);
    // or
    const results = await skygear.publicDB.save([record]);
    console.log(results);
  } catch (e) {
    console.log(e);
  }
});
```

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
@Steven-Chan I think the simplicity is:

1. No more partial success return on the client side
1. Simplified the option of atomic save

The tradeoff is:

1. Overhead when firing multiple save request.

Any others? I suppose you got more idea since u created the issue :) That will help facilitate discussion and push the decision quicker?
