### ISSUE TITLE
[CMS] Multilingual support

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#229]
# Description

Multilingual models is application specific. See if we can assume one generic models for multi languages support?

### Using JSON
- Languages table to specify supported languages
- Have language switch tabs in multilingual support models form, multilingual field will store as JSON

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
Just want to add that when we have multiple language in CMS, we will need to consider how it works at client API. (And that is probably more difficult than the CMS interface @@)

Some thought:

1. Don’t confuse CloudDB query API with translation API, say if we magically return only a single locale string for all string columns, developer may confuses or it may prevent them to do something. Rails have a lot of plugins do magical things on activerecord, if we decide to go with magic in CloudDB api, let’s at least study how those framework handle it... 

2. I have seen other BaaS have a separate set of Content API and tables for that, it might be easier as it won’t touch or do magic on the DB API layer. Instead the trade off is performance penalty of another query to another table for the translated strings.

**Comment by tensiuyan** [comment]
talked with PMs. Most project needs multi-lingual functions. Eng, Traditional Chinese & Simplified Chinese.

**Comment by chpapa** [comment]
@tensiuyan Not sure if it is too technical for u, but I guess if we want to do it earlier (maybe right after CMS Next completed basic feature?), we would also want to know how most projects structure their database for multi-lingual, to help us design the DB structure we support (or crazy idea: we support more than 1 DB structure!?)
