### ISSUE TITLE
auto master-slave in multi-server deployment

### ISSUE THREAD

**Issue by hidden-dimensions** [SkygearIO/features#236]
# Description

In `skygear-server` .env there is a config option: `SLAVE` intended to disable certain features when multiple running server instances. However such options make deployment non-trivial and also create single point of failure. Suggest to introduce a auto mechanism like voting or even a db atomic lock to select a master to run those "single operations", and re-select periodically / have keep-alive to handle machine down.

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
@hidden-dimensions I think this is duplicated with #230 

I will copy-paste your comment above to #230 , and maybe you can chip in there as well.
