### ISSUE TITLE
Custom domain supports HTTPS redirection

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/features#247]
# Description

**Add 2-3 sentence description of your feature**

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by carmenlau** [comment]
If we enforce all custom domains redirect to https, that would be simpler. So We need to decide if this is a configurable setting (e.g. allow user to set it in portal).
