### ISSUE TITLE
Forgot password and welcome email in Skygear portal

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#25]
# Description

Plugins to implement forget password and welcome emails features

There is an existing plugins: https://github.com/skygeario/forgot_password/

# Design/Specification

* Workflow:
  * Call `forgotPassword(email)` from client-side
  * The respond is always success even if the email address was not found, if `FORGOT_PASSWORD_SECURE_MATCH` is set to TRUE. (Hence users are expected to display something like *If a matching account was found an email was sent to user@email.com to allow you to reset your password.* after forgot password was requested.
  * `FORGOT_PASSWORD_SECURE_MATCH` is set to FALSE by default, which will return ResourceNotFound if the email doesn't match.
  * If `FORGOT_PASSWORD_WELCOME_EMAIL` is set to TRUE, send an *Welcome Email* when new user signed up.
* Portal Setting (Under `User Auth` > `Forgot Password` / `Welcome Email`)
  * Setting (Enable, Sender, From, Reply To)
  * Welcome Email Template (sent when new user signed up and enabled)
  * Forgot Password Email Template (sent when password reset was requested)
  * Reset Password HTML Template
  * Reset Password Success HTML Template
  * Reset Password Error HTML Template
  * Each Email Template / HTML Template in Portal have a "Try" button for a preview.
  * Each template should have the following fields:
    * From Email Address
    * Subject
    * Reply to
    * Content
    * Redirect URL (only applicable for emails)
    * URL Lifetime (only applicable for HTML templates)
  * Content are expected to be an HTML / plain text editor with placeholder variable. The list of placeholder variable should include all the fields under the User table, and something like `[[url]]` to include link to the confirmation page.

## Sample code

```
SKYContainer.default().forgotPassword(email: “chpapa@gmail.com”)
skygearContainer.forgotPassword(“chpapa@gmail.com”)
skygear.forgotPassword(“chpapa@gmail.com”)
```

# Related Issues

- Server Issues
  - SkygearIO/forgot_password#9
  - SkygearIO/forgot_password#10
  - SkygearIO/forgot_password#11
  - SkygearIO/forgot_password#12
- Client Issues
  - SkygearIO/skygear-SDK-Android#123
  - SkygearIO/skygear-SDK-JS#192
  - SkygearIO/skygear-SDK-iOS#92
- Portal Issues
  - https://trello.com/c/M7QhTYqM/118-skygear-forgot-password-and-welcome-email-portal-setting
  - oursky/skygear-portal#262
- Guides Issues
  - SkygearIO/guides#56

# Progress Tracker

- [x] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
Due to the proposal at #68, the API of this feature issue need to change.

The change is, it was assumed that we can uniquely identify users by an email address, however with the change introduced at #68, it is no longer valid.

**Comment by rickmak** [comment]
@Steven-Chan will confirm does an API change in required after inspecting each SDK. For JS/Java, the current API should be extensible. Need to confirm on Obj-C.
