### ISSUE TITLE
Improve security for storing current user profile and access token in client app

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#250]
# Description

Currently ios is using `UserDefaults`, android is using `SharedPreferences `, and js is using local storage. To improve the security, we should use a more secured store for current user data.

Some reference:

iOS keychain services: https://developer.apple.com/documentation/security/keychain_services
example: https://developer.apple.com/library/archive/samplecode/GenericKeychain/Listings/GenericKeychain_KeychainPasswordItem_swift.html#//apple_ref/doc/uid/DTS40007797-GenericKeychain_KeychainPasswordItem_swift-DontLinkElementID_7
Android keystore system: https://developer.android.com/training/articles/keystore

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
👍 for this.
