### ISSUE TITLE
External DB user profile synchronization 

### ISSUE THREAD

**Issue by kaojohnny** [SkygearIO/features#287]
# Description

When desigin #256, we considered syncing auth data for user's external DB (such as for some attributes in their user profile). There were 3 approaches discussed:

1. User provide an external DB, and we sync it for the user
1. Use an "eventually consistent hooks"
1. Use a two-phase commit hook for real time data update

### Approach of  "eventually consistent hook"
| Action | Hooked Cloud Function |
| -------- | -------- | 
| `user_object` | `blocking_user_sync(user)`<br>`user_sync(user)`<br> |

and their behavior as:

1. `user_sync` is an `AFTER`, `ASYNC` hook, its implementation could be simple after async hook like other hooks, or it can be optimized by other mechanisms.
2. `blocking_user_sync` is an `AFTER`, `SYNC` hook. `blocking_user_sync` is especially useful when consistency is important to the application. Skygear next will rollback DB if hook failed.

In this issue, we should complete the following tasks:
1. naming of hooks
2. implementation detail of hooks
3. Consider concurrent use cases, like:

| Req 1 | Req 2| Remarks 
| ---- | ---- | ---- |
| enable_op |  | Req 1 called |
| after_enabled_sync() | disable_op | Req 2 called |
|  | after_disabled_sync() | |
|  | [external system update user status to disabled] | For network latency reason, req 2's hook got called first |
| [external system update user status to enabled] | | Oops

this issue happens when two requests happens concurrently in race condition. e.g. one users logged in two devices at the same time and call the ops above.

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
@kaojohnny updated the description to follow the issue format
