### ISSUE TITLE
Verify requests from auth gear and gateway in CF & microservices

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#300]
# Description

There are 2 parts we need verification.
1. CF need to verify if the request are from gateway, so the injected context (current auth user) can be trusted.
2. webhook (should be CF) need to verify if the request are from auth gear.

We (@carmenlau, @Steven-Chan)  had a short discussion on this, and here is the note. We may need to draft a detailed spec for this.

- the program that wrap user function (i.e. fission environment / openfaas watchdog) is responsible for verifying gateway request
- if the user function is deployed independently, the responsibility of verifying gateway request go to the developer, so we need to tell them how we sign the request
- SDK is responsible for verifying auth gear request
- secrets for verifying gateway and auth gear request are defined per app
- we introduce predefined cloud code secret (vs user defined secrets using skycli api and used in cloud code secret config)
- the secret for verifying gateway request is a predefined cloud code secret
- if cloud code config specify that a function is a auth gear web hook, the secret for that is also a predefined cloud code secret

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by tensiuyan** [comment]
update the specification since this is now dealt by network policy.
