### ISSUE TITLE
Get current user from request context in cloud code

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/features#302]
# Description

**Add 2-3 sentence description of your feature**

## Scenario

Developer should be able to get current user from the request content in cloud code

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
@tensiuyan I'm confused if it is a feature requirement or skygear-server's issue? Feature requirement should be a new features with design / spec needed.

**Comment by tensiuyan** [comment]
The feature is developer need to be able to access Current User in the cloud functions module.
