### ISSUE TITLE
Add skygeario related custom domains to https://publicsuffix.org/

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#315]
# Description

We should add all of the suffix domain names we provide for services in https://publicsuffix.org/

Aims at Skygear 2.0 portal and also existing 1.0 domains.

**Comment by tensiuyan** [comment]
HKPC: staging, prod
Skygear: staging, prod

**Comment by carmenlau** [comment]
PR merged!
https://github.com/publicsuffix/list/commit/8260e5f69dd58fc222cca0b2d81aeee5bb2d10fc
