### ISSUE TITLE
Revisit loginIDs configuration for email verification, forgot password, welcome email handling

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#323]
# Description

Need to update the spec to cover following use cases:
- Update loginIDs configuration with type to achieve
     - Support email related features
     - Support loginIDs normalization in future (email, phone, case insensitive id...etc)
- Consider user have more than 2 emails
      - If user have more than 1 emails as login ids, send welcome email to all emails
      - forgot password api require email, so reset password email should be sent to that email. all loginids password should be reset?
      - Which fields require verification should be configurable under verification config. Double check current verification setting, we should allow user to verify more than 1 email fields
- See any other use cases we should cover

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
Two thoughts.

> If user have more than 1 emails as login ids, send welcome email to all emails
I think our API should make it flexible, they can send a welcome email to just one emails, specific email address, or all? I think for welcome email, most case just 1 email address is fine.

Other issues are:
* Should we have the concept of primary login ID / primary email address?

**Comment by louischan-oursky** [comment]
@kiootic Please also consider the above Ben's comment in your specification.

**Comment by chpapa** [comment]
> @kiootic Please also consider the above Ben's comment in your specification.

Thanks. I think it is about the PR #325? Seems already kind of considered.

(Oh but the PR didn't link back to this issue...)

**Comment by louischan-oursky** [comment]
Here are some goals we need to achieve

---

1. Support implicit login ID key
As in "Login with your email, phone number or username"

1. Support login ID in a realm
Combine email and a realm to form a password principal
email: louischan@oursky.com
realm: teacher
email: louischan@oursky.com
realm: student

1. Support multiple login IDs under the same login ID key natively
So that we do not need to rely on naming convention like (`email`, `email2`, `email3`)
Note that we need to adjust the implementation of verification.

1. Support login ID normalization
    - email normalization by applying a RFC5322 addr-spec parser, ASCII lowercase the domain, ASCII lowercase the local-part
    - phone normalization by validating the phone number is in E.164 format with libphonenumber
    - unicode case folding

1. Support tagging primary email address

1. Support configuring welcome email
    - Do not send at all
    - Send to primary email address
    - Send to all email addresses

1. All password principals of a single user must share the same password

**Comment by chpapa** [comment]
>     3\. Support multiple login IDs under the same login ID key natively

So this also meant we will use Login ID key convention for semantic meaning (such as `email` must be email address?)

**Comment by louischan-oursky** [comment]
> So this also meant we will use Login ID key convention for semantic meaning (such as email must be email address?)

No, we will have a configuration to allow the developer to tell us which login ID key is email

The configuration looks like

```yaml
login_ids:
  email:
    type: email
  phone:
    type: phone
  username:
    type: plain
  handlename:
    type: unicode-case-folding
```

**Comment by chpapa** [comment]
> No, we will have a configuration to allow the developer to tell us which login ID key is email

Thanks, very clear to me now :)
