### ISSUE TITLE
Identity APIs

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/features#329]
# Description

Main objective: Ensure all identity providers (e.g. password, oauth, custom token) are well-supported on API level.

- Consistent API on the principal associated with current session (e.g. `current_login_id`, `current_oauth_id`, `current_custom_token_id`)
- Consistent API on getting list of associated principals (e.g. getting login IDs, linked OAuth accounts, associated custom tokens)
- Consistent API on creating/deleting principals (e.g. create/delete login IDs, link/unlink OAuth accounts)
- Specify the consistent method to obtain metadata about the principal for internal/external usage (e.g. sending welcome email to OAuth accounts, synchronizing user metadata from external profiles)

# Related Issues

- Spec PRs
  - [x] https://github.com/SkygearIO/features/pull/334
- Server Issues
  - [x] https://github.com/SkygearIO/skygear-server/issues/974
- Client Issues
  - [ ] https://github.com/SkygearIO/skygear-SDK-JS/pull/553
- Guides Issues
  - TODO

**Comment by chpapa** [comment]
For the record, the idea of a Principal APIs is highly debatable and unless there are very clear arguments, demonstrated by sample code and API spec that it is better than existing APIs interfaces, I think we shouldn't assume this will be implemented.
