### ISSUE TITLE
User Metadata in 2.0

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/features#331]
# Description

As proposed at #325 , we auto-populate user metadata with Login IDs.

It needs to be decided if it is a good things or not before we launch to avoid backward incompatiable change, before Skygear 2.0 launch.

- Should auth gear auto-populate user metadata
- Should auth gear allow developer to specify validation of metadata
- Should auth gear specify meaning of some keys in metadata for future use (management portal/auth UI kit)

## Scenario

**Put list of Scenario how developers will use this API**

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
@kiootic revised a bit with proper lables added.

**Comment by chpapa** [comment]
Seems we are not going to address this before launch anyway.
