### ISSUE TITLE
Remove anonymous login

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/features#333]
# Description

Anonymous login can be implemented easily using alternative login ID key. We can remove anonymous login to reduce maintenance burden.

## Scenario

Currently, to signup anonymously:
```typescript
const user = await signupAnonymously();
// we now have a valid user object and session
// however, if the access token is lost or expired, the user cannot be login
// again and is lost forever.
```

Alternatively, under the new login ID design, we can:
```typescript
const uid = uuid(); // e.g. 4F824578-8251-4152-835F-07FC89AFD37D
const password = cryptoRandom(16); // e.g. 07e52ecd66b6bea05be38057a6d4453b
const user = await signup({"uid": uid}, password);
// we now have a valid user object and session
// to emulate current behavior, simply discard uid and password

// we can also upgrade to normal user later if we save password (and uid):
const email = prompt();
const newPassword = prompt();
await addLoginID({"email": email});
await changePassword(newPassword, password);
await loginWithEmail(email, newPassword);
await removeLoginID(uid);
```

# Portal Design

**Remove this section if the feature have no Portal**

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
@kinetic help provide like sample code for how anonymous user is implemented now vs custom login key so we can review the usability of the code and implications?

**Comment by kiootic** [comment]
@chpapa updated to add scenarios.

**Comment by chpapa** [comment]
I think it is too implicit, doesn't sound like out-weighting the maintenance burden (actually I don't recall we have a lot of issues with anonymous login before)

One thing we do get asked multiple times is to make it easy to upgrade anonymous account to non-anonymous account.

Another thing is Skygear v1 create anonymous users by default, we can reconsider is it a good behavior in v2.

But that should be another discussion, so I suppose we will close this issue first as it doesn't seems to make sense to remove anonymous signup.

**Comment by kiootic** [comment]
I think you mean it's too explicit. I agree more work is required to implement the proposed way, however it is much more consistent than creating a user that is impossible to login again if access token is lost/expired, considering we don't have a way to refresh access tokens.

I would like to know if it is used widely in v1? If we should keep it in version next, we should specify this feature in details, including possible use cases.

**Comment by chpapa** [comment]
> I think you mean it's too explicit. I agree more work is required to implement the proposed way, however it is much more consistent than creating a user that is impossible to login again if access token is lost/expired, considering we don't have a way to refresh access tokens.
> 
> I would like to know if it is used widely in v1? If we should keep it in version next, we should specify this feature in details, including possible use cases.

I'm thinking if we should try to not even default to anonymous users in the first place.
