### ISSUE TITLE
Improve uniqueness checking for LoginID

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#339]
# Description

Improve uniqueness checking for LoginID with common security issues:

- [x] Default case-insensitive for email 
- [x] Default case-insensitive for loginID (could be disabled)
- [x] Normalize non-ASCII username using NFKC as [recommended here](http://www.unicode.org/reports/tr36/#Recommendations_General)
- [x] Avoid confusing homoglyphs username based on some libraries like [confusable_homoglyphs](https://confusable-homoglyphs.readthedocs.io/en/latest/index.html)
- [x] Options to disallow non-ASCII username
- [x] Normalization of email address / phone number
- [x] Options to ignore `.` and  email address after `+` for uniquness checking
- [x] Disallow loginID that is confusing ([Djagon List](https://github.com/ubernostrum/django-registration/blob/1d7d0f01a24b916977016c1d66823a5e4a33f2a0/registration/validators.py))

# API Design

**Remove this section if the feature have no API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
@kiootic If something listed above are easy, feel free to add it first :) cc: @louischan-oursky

**Comment by louischan-oursky** [comment]
I discovered a related RFC

- [PRECIS Framework: Preparation, Enforcement, and Comparison of
           Internationalized Strings in Application Protocols](https://tools.ietf.org/html/rfc8264)
- [Preparation, Enforcement, and Comparison of Internationalized Strings
                  Representing Usernames and Passwords](https://tools.ietf.org/html/rfc8265)

**Comment by carmenlau** [comment]
Would like to bring this up, currently signup user with same email in different cases will create multiple users.

Maybe we need to implement the point 1 first (Default case-insensitive for loginID). If the cases in display is not that important, maybe we can just store the lower case of login id when case-insensitive is enabled.

**Comment by carmenlau** [comment]
Had a short discussion with @kiootic. Since email should be case insensitive by nature, rather than using a case-insensitive setting for loginID, that would be better to do the normalization by login id type.

Email should be case-insensitive, we will store the normalized value separately. All the user facing login id data will be the original input data (e.g. login id in identify when calling `/me` api). Normalized value will be used only for login or user query.

Let me know if it looks good for you. If so, we will do the case-insensitive version for email first. @louischan-oursky @chpapa

**Comment by chpapa** [comment]
@carmenlau @louischan-oursky @kiootic I assume it is the pt5 in the original message. Email address and phone no definitely need normalization beyond standard string LoginID processing.

However:
1. Email address are NOT case insensitive by nature -- only domain name part is case insensitive. Please beware of it. reference: https://github.com/django/django/blob/1.9.2/django/contrib/auth/base_user.py#L19-L31
1. To clarify we need both case-insensitivity for loginID, and normalization of email address, eventually.

The rest I think is fine

**Comment by kiootic** [comment]
> Email address are NOT case insensitive by nature

Technically speaking, the local part of email should be only interpreted by the mail server, so we should not do any processing on it. However practically, most mail server (at least in my experience) would treat the local part as case-insensitive. Moreover, as you mentioned at point 6, `+` is sometimes used for labeling, `.` is ignored by Gmail, etc. I don't think we should offer tons of config for email normalization, but rather use a practically correct interpretation of local part.

**Comment by chpapa** [comment]
@kiootic 

>  I don't think we should offer tons of config for email normalization, but rather use a practically correct interpretation of local part.

We SHOULD provide the configuration for common things people want to ignore in uniqueness checking for email address, such as parts after `+` and ignore `.`; 

These are important -- for Enterprise Software etc, they may have real users whose email address diff with `.`, and would use our default that don't ignore `.`; (Assume our default is that) For consumer software, they may want to ignore `.` to avoid duplicated users.

However, we SHOULD also provide a sensible default that most developers don't need configuration.

> Technically speaking, the local part of email should be only interpreted by the mail server, so we should not do any processing on it. However practically, most mail server (at least in my experience) would treat the local part as case-insensitive.

This is not "Technically speaking", it is RFC. Also not "practically" -- not everyone uses gmail, at least MS Exchange and exim4 as I know by default treat email case sensitive.

**Comment by kiootic** [comment]
> We SHOULD provide the configuration for common things people want to ignore in uniqueness checking for email address, such as parts after + and ignore .;
> These are important -- for Enterprise Software etc

I suppose you would like to cater for 'enterprise developers' and 'consumer developers' equally, is that right? Therefore we'll have at least 3 config options, with some sensible defaults:
- case insensitive local part (default false?)
- ignore local part after '+' (default false?)
- ignore '.' (default false?)

Personally I'd prefer default values of (true, false, false) respectively.

> This is not "Technically speaking", it is RFC. Also not "practically" -- not everyone uses gmail, at least MS Exchange and exim4 as I know by default treat email case sensitive.

My point is that, the RFC has left the interpretation of local-part to mail server, and most commonly used, consumer facing mail service have some convention that many users expects, such as case insensitive local-part.

I have not used the mentioned mail servers before, but a cursory glance at [exim's documentation](https://www.exim.org/exim-html-current/doc/html/spec_html/ch-message_processing.html#SECID230) seems to indicate case-insensitive local-part for compatibility with Unix username.

**Comment by chpapa** [comment]
> I suppose you would like to cater for 'enterprise developers' and 'consumer developers' equally, is that right?

Enterprise vs consumer are just examples, it is not a very meaningful definition here anyway. Just to illustrate how both ignoring `+` part and `.` or not are common and essential that we need an option. 

> but a cursory glance at [exim's documentation](https://www.exim.org/exim-html-current/doc/html/spec_html/ch-message_processing.html#SECID230) seems to indicate case-insensitive local-part for compatibility with Unix username.

Noted, sorry for my bad memory. But anyway since it is in RFC, and an email server could handle it like that, and we could run into the troubles.

> Personally I'd prefer default values of (true, false, false) respectively.

I agree with the default.

**Comment by carmenlau** [comment]
I found some problems when I work on this, since we support login with login id without key. Assume the app supports login with username or email, and the email normalization setting is (true, true, true).

1. One user signup with username `test+a@example.com`, we stored `test+a@example.com` as the normalized id.
1. Another user signup with email `test+anything@example.com`, we stored `test@example.com` as the normalized id.
1. Someone login with login id `test+a@example.com` and no key is specified, 2 users record will be matched.

Thinking how this case should be handled. 🤔

**Comment by chpapa** [comment]
Exact match first, than normalized?

**Comment by kiootic** [comment]
I think if no key is specified, no normalization is performed and it would match username `test+a@example.com`. Anyways, this seems an issue on app developer side to allow this kind of situation to happen.

**Comment by carmenlau** [comment]
In future we may support more login id type which has different normalization, so there will still be chance that the normalized id matched multiple records.

> Exact match first, than normalized?

I think it is good. 

> I think if no key is specified, no normalization is performed

I think that may not be good for the UX. If app developer configs the app to ignore words after `+`, they will assume that they should be able to login without  `+`.

> Anyways, this seems an issue on app developer side to allow this kind of situation to happen.

I agree.

Here is my suggestion and some notes, 

1. For login without key, try exact match first, than normalized. If servers match multiple records for normalized value, error will be returned.
2. For login with key, we will match the normalized value directly.
3. In order to give more flexibility, I think the normalization config should be per id key, instead of per type. That means app developer can config the app to have 2 email type login id with different normalization config.
4. Since changing the config will not migrate the db data, so that may cause unexpected behaviour for user who want to login the existing account.

Thoughts?

**Comment by kiootic** [comment]
> I think that may not be good for the UX. If app developer configs the app to ignore words after `+`, they will assume that they should be able to login without `+`.

My point is that, the developer should not allow this situation to happen in the first case, as there are no objective resolution of this conflict. If the developer really want to have this, they should instruct how to resolve the correct user (i.e. manually specifying the key when logging in).

Also, this has been [discussed](https://github.com/SkygearIO/features/pull/325#discussion_r298005724) before, and my opinion is that if key is not provided, exact match is used.

**Comment by carmenlau** [comment]
@kiootic I got your point now.

We just have a short discussion on that maybe solve the problems, here is a short summary.

1. Actually the normalization is trying to improve the login id uniqueness, so the normalization setting should be per type instead of per id key.
1. The normalized value technically should be the login id that identify the identity. So we should store the normalized value to the login id, in case user need to original value to display, they should store it themselves (e.g. store to meta data and get it from the hook etc.). 

> My point is that, the developer should not allow this situation to happen in the first case, as there are no objective resolution of this conflict. If the developer really want to have this, they should instruct how to resolve the correct user (i.e. manually specifying the key when logging in).

After the first 2 points, the conflict may still exists. The login id may matches multiple records through different type normalization. How about if we try checking the password? In case 2 principals have the same password, then throw error? This is a rare edge case. If we handle it this way, we can have better UX for login without key api.

I will write a spec for this issue.

**Comment by kiootic** [comment]
> in case user need to original value to display, they should store it themselves

I don't have a strong opinion on this, but I want to mention that it is a common practice that storing both pre-normalized and normalized value in the database.

> How about if we try checking the password? In case 2 principals have the same password, then throw error? This is a rare edge case. If we handle it this way, we can have better UX for login without key api.

I don't think it is a UX issue, it's rather a security issue. In my opinion, we should not try to guess the intention of user/developer in this security-critical path, which is why I suggest to have a static behavior, independent of the query result.

**Comment by chpapa** [comment]
> I don't have a strong opinion on this, but I want to mention that it is a common practice that storing both pre-normalized and normalized value in the database.

How common? Any major auth system do it? I'm a bit skeptical on this...

I think it might be convenience for the purpose of displaying the LoginID though, maybe in metadata?

> I don't think it is a UX issue, it's rather a security issue. In my opinion, we should not try to guess the intention of user/developer in this security-critical path, which is why I suggest to have a static behavior, independent of the query result.

The only static behavior would be to throw error here, let's say there are two loginIDs: ben+sample@gmail.com (as LoginID) and ben@gmail.com (as Email Address), logging in with ben+sample@gmail.com is ambiguous without loginID key.

So either we treat loginID + password as a tuple, and try which one is correct; Or throw an error whenever a loginID could match more than one loginID after normalization.

In fact, I think one could argue we should stop these type of ambiguous from happening at Sign up in the first place....

**Comment by kiootic** [comment]
> How common? Any major auth system do it? I'm a bit skeptical on this...

To clarify, most online tutorials to recommend indexing the normalized value and store pre-normalized value in database. I do think it is acceptable if we can provide pre-normalized value in API so that developer can save it on their own.

> logging in with ben+sample@gmail.com is ambiguous without loginID key

It is only ambiguous if we do normalization when logging in without key. If we do not normalize it, then only one login ID would be matched.

> loginID + password as a tuple, and try which one is correct

This is what I call dynamic behavior, which may lead to potential security issues. Instead, I'd rather want the behavior to be as simple as possible, without depending on result of many queries:
- provide login ID key: match on normalized login ID
- not provide login ID key: match on exact login ID

> In fact, I think one could argue we should stop these type of ambiguous from happening at Sign up in the first place....

I agree, but the configuration can change anytime, so this ambiguity is unavoidable (suppose the developer change the type of login ID key).

**Comment by chpapa** [comment]
> It is only ambiguous if we do normalization when logging in without key. If we do not normalize it, then only one login ID would be matched.

I think it is ambiguous, coz there are no "if we do not normalize it". If the auth system has an email address `ben+sample@gmail.com`, and it always strips anything after `+` for email login ID, the so-called exact match is surprising to both end users and devleopers, and the so called "static" behaviour would have security implication too (e.g. make it easy for people who knows it intentionally collide the username.

> This is what I call dynamic behavior, which may lead to potential security issues.

Actually I think it is okay, can you suggest one potential security issue if we match both loginID + password as a tuple?

In fact, the static solutions you suggested above (i.e. disable the "normalization" depends on login with or without login key) could have security issues of making it easy for users to collide and hijack the username.

**Comment by carmenlau** [comment]
Another round of discussion with @louischan-oursky 

There will be security issue, if we test the principals with password. If a user get the error, he will know that another user have similar login id with him. He can change his password and use the original password login again, then he will login as the other user account. 🙈

So I think maybe we can consider following?

1. Like @kiootic suggest, don't normalize the input and do extract match. 
1. Do normalization, throw error if multiple records are matched.

**Comment by chpapa** [comment]
>     1. Like @kiootic suggest, don't normalize the input and do extract match.

Don't do that, I think it surprises users (why the configuration got disabled if login without key?); And makes it possible for people to redirect the user to login in another account. (Although unlikely, only if he knows the password already)

> There will be security issue, if we test the principals with password. If a user get the error, he will know that another user have similar login id with him. He can change his password and use the original password login again, then he will login as the other user account. 🙈

I don't really understand this...

Say if someone tries to collide my `ben@oursky.com` with a loginID of `ben+test@oursky.com`...

1. When he login with `ben+test@oursky.com`:
    1. with a correct password, he got logged into his account
    1. with a incorrect password, he got a password incorrect error. 

What does it meant by "If a user get the error, he will know that another user have similar login id with him. He can change his password and use the original password login again, then he will login as the other user account."

**Comment by kiootic** [comment]
> If the auth system has an email address ben+sample@gmail.com, and it always strips anything after + for email login ID, the so-called exact match is surprising to both end users and devleopers.

I'll argue that, if developer knows we strips anything after +, they should have read the documentation already, so whatever behavior would not be 'surprising'. If the developer have not read the documentation, then I'll say it is possible that this normalization is the surprising behavior here.

> make it easy for people who knows it intentionally collide the username
> could have security issues of making it easy for users to collide and hijack the username.

I don't quite understand this, do you mean if I signup using email `a+test@gmail.com` and always log in using `a@gmail.com`, attacker can sign up using `a@gmail.com` and trick the user logging in as wrong user?

As I mentioned before, the entire scenario (collision of normalized login ID and unnormalized login ID) does not make sense, and it would be developer's problem to allow this scenario.

> Do normalization, throw error if multiple records are matched.

I think this is acceptable. What I'm against is having different behavior after matching multiple records as suggested previously (i.e. trying password for multiple user).

**Comment by chpapa** [comment]
> I'll argue that, if developer knows we strips anything after +, they should have read the documentation already, so whatever behavior would not be 'surprising'. If the developer have not read the documentation, then I'll say it is possible that this normalization is the surprising behavior here.

The surprising part is, the documentation would tell you if you set the option of "uniqueness checking will treat a+b@c.com identical to a@c.com". This is what the documentation would tell you. 

What the documentation won't tell you (or, would be very difficult for normal users to understand) is, the option does not apply to login without Key ID. 

So I can't agree with your argument.

> What I'm against is having different behavior after matching multiple records as suggested previously (i.e. trying password for multiple user).

This is not different behavior, in fact, good auth system ALWAYS treat the tuples of LoginID + Password as something to check against. I don't see any "different behavior" here.

It is very basic security best practices, that auth system should not throw different errors for password incorrect vs login ID not found.

**Comment by chpapa** [comment]
> I don't quite understand this, do you mean if I signup using email `a+test@gmail.com` and always log in using `a@gmail.com`, attacker can sign up using `a@gmail.com` and trick the user logging in as wrong user?

Yes, that's assuming the hackers already knows my password and want to trick me into loggin into another account to do something they want to mislead me into.

**Comment by kiootic** [comment]
> What the documentation won't tell you (or, would be very difficult for normal users to understand) is, the option does not apply to login without Key ID.

We can just tell user about it? Something like `if you enabled email normalization, it would be applied for signup and logging in with specified login ID key`.

> This is not different behavior, in fact, good auth system ALWAYS treat the tuples of LoginID + Password as something to check against. I don't see any "different behavior" here.

The different behavior is that the previously proposed solution checks multiple tuples of (login ID, password), while I'd prefer we'll always check at most single tuple when logging in.

> Yes, that's assuming the hackers already knows my password and want to trick me into loggin into another account to do something they want to mislead me into.

If the attacker knows your login ID and password, you're having a bigger problem there. I don't think this attack is practical.

**Comment by chpapa** [comment]
> We can just tell user about it? Something like if you enabled email normalization, it would be applied for signup and logging in with specified login ID key.

Quite impractical, it requires in-depth understanding like why there are no login ID key login, which usually users would only know the feature when they use it. So it will be a hard to grab concept and would surprise people

> while I'd prefer we'll always check at most single tuple when logging in.

If it is a “tuple” that would be a “single check” anyway. Login ID is just an index here to help speed up the checking

Plus we still don’t have any samples of why that behavior is problematic?

The only problem I see is, if somehow two tuples really collide, we still throw the same auth invalid error, will reveal the information of two loginIDs have the same password. Although it is rare but could be possible, we may want to ignore it or throw a general system error in this case

> If the attacker knows your login ID and password, you're having a bigger problem there. I don't think this attack is practical.

No, that could be very different. Able to access all of my information, vs leading me to do certain action is two different attacks, which is practical.

**Comment by kiootic** [comment]
> If it is a “tuple” that would be a “single check” anyway. Login ID is just an index here to help speed up the checking

Previously it is suggested to query all (login ID, password) tuples and check the input password against all tuples. This is multiple checks, and may have potential security problems.

> The only problem I see is, if somehow two tuples really collide, we still throw the same auth invalid error, will reveal the information of two loginIDs have the same password. Although it is rare but could be possible, we may want to ignore it or throw a general system error in this case

I do think this occurs more than you think, considering the existence of top 10 password list.

> Plus we still don’t have any samples of why that behavior is problematic?

And I don't see any proof that it is not problematic.

I know we can't proof something is completely secure, but most existing auth systems either support no normalization out-of-box, or mandates normalization on all login IDs, so I can be sure that no significant issues with these two approaches. Therefore I'll suggest a more radical option: do not allow logging in without login ID key.

> No, that could be very different. Able to access all of my information, vs leading me to do certain action is two different attacks, which is practical.

Indeed it is different. I think that the former risk has much higher value than the latter one in most cases, so I considered it impractical (i.e. most likely attackers would not attempt to trick the user, but just go in the account directly).

**Comment by chpapa** [comment]
@kiootic i think when you said it could be problematic or have security implications, unless it is obvious, you should give a clear example. Otherwise it is hard for us to have any meaningful conversation

> I know we can't proof something is completely secure, but most existing auth systems either support no normalization out-of-box, or mandates normalization on all login IDs, so I can be sure that no significant issues with these two approaches. Therefore I'll suggest a more radical option: do not allow logging in without login ID key.

Can’t follow the logic here. So we are already suggesting and concluding to do normalization on all loginIDs already, any objection? 

> I do think this occurs more than you think, considering the existence of top 10 password list.

However the match doesn’t just about password, but also need the loginID to be matched, accidentally

> Indeed it is different. I think that the former risk has much higher value than the latter one in most cases, so I considered it impractical

Getting information or tricking user to do something might have different values depends on context.

**Comment by chpapa** [comment]
To conclude a bit, I think we now basically agreed to:

LoginID always have the same uniqueness checking and normalization no matter login via which APIs

We have the following choices when loginID collide:

1. Throw invalid auth once loginID is ambiguous
2. Treat LoginID and Password as a tuple to auth. Throw invalid auth if two tuples matches

Alternatives:
1. Take away login without key at all (unlikely, it is a common feature requirements)
1. Do not respect uniqueness checking on login without key (could surprise lots of users)

Maybe we can focus our discussion on the choices above?

**Comment by kiootic** [comment]
> i think when you said it could be problematic or have security implications, unless it is obvious, you should give a clear example. Otherwise it is hard for us to have any meaningful conversation

To summarize my opinion: I'm not sure if any of the purpose solutions is secure, but when discussing the security aspect, it's safer to assume it is not secure if not proven otherwise. Most existing system either have no normalization, or normalize a single login ID type. Therefore I suggest using the proven method of doing normalization depending the login ID type only and do not accept logging in without login ID key.

> LoginID always have the same uniqueness checking and normalization no matter login via which APIs

But we don't? We will have different normalization for `email` and `phone` login ID, and no normalization at all for `raw` login ID.

> 1. Throw invalid auth once loginID is ambiguous

I think this is acceptable.

> 2. Treat LoginID and Password as a tuple to auth. Throw invalid auth if two tuples matches

I don't know if it is secure, so I don't suggest using this.

> 1. Take away login without key at all (unlikely, it is a common feature requirements)

I don't think it is a common feature requirements. If needed, developers can implement it themselves according to their requirements.

> 2. Do not respect uniqueness checking on login without key (could surprise lots of users)

I also don't think it is surprising. If developers say they're surprised since they don't read the documentation (assuming our documentation is readable enough), I don't think we are to blame.

**Comment by chpapa** [comment]
@kiootic there are two points we have discussed many times throughout development of skygear, which you seems don’t agree with but didn’t give a reason and repeatedly state the same old argument. I will repeat the points below but I hope we don’t have to keep repeating them in future. 

Please acknowledge by replying below if you understood them, or If you have problems understanding it please let me know specifically which part, or we can also discuss it face to face in next product meeting. 

> I don't think it is a common feature requirements. If needed, developers can implement it themselves according to their requirements.

It is common feature as we can see there are many services out there that users can login by different login IDs. A random example is Facebook can login with emails or phone numbers. There are no lack of examples. For features as common as these we should take care of it and have a obvious way to do that.

“I don’t think” is not a good arguments. Real world examples are.

> I also don't think it is surprising. If developers say they're surprised since they don't read the documentation (assuming our documentation is readable enough), I don't think we are to blame.

You can’t take this point of view: anything written on documentation are no surprise. 

There are common sense / expectation. Common sense are what are the common practices in the software industry; expectations are consistency between how things are handled in skygear.

Moreover, you can never expect users will read ALL documentation before they start using any software libraries.

In this example:

1. If we normalize loginID for uniqueness checking in all login API except one, it is surprising
2. If we try to explain the concept of login with or without specifying login ID type, altogether with uniqueness checking of loginID, we have to make sure the users read both sections. Given it is a minor details and quite an edge case when people first try to understand the software, they need to read the documentation in very fine details to actually notice it

So when we design the system, we shouldn’t make it unnecessarily complication and assume it is ok if we write the documentation. Instead we should always try to follow best practices / common practices, keep consistency between our design, and make things as self-explanatory as possible

**Comment by chpapa** [comment]
Regarding the design, unless we got more idea, let’s assume the one which throw invalid auth immediately once login ID is ambiguous? As agreed between me and @kiootic so far?

I did some quick research, OWASP recommend username to be unique, so agree with @kiootic that maybe we shouldn’t check same username with different passwords as a user.

**Comment by kiootic** [comment]
> It is common feature as we can see there are many services out there that users can login by different login IDs. A random example is Facebook can login with emails or phone numbers. There are no lack of examples. For features as common as these we should take care of it and have a obvious way to do that.

We've discussed on it before, and I do understand what you mean. To clarify, I mean I don't think it is a feature requirement that it is commonly requested to support it natively. Also, most auth framework does not support it natively. Considering the developer can implement it with minimum effort at client side, I don't think it is necessary.

> You can’t take this point of view: anything written on documentation are no surprise.

I agree with you on this point, which is why I included the assumption that our documentation is readable enough. I don't expect the user ignores tutorials, documentation website, and auto-complete documentation in editor, then says it's our fault.

> Moreover, you can never expect users will read ALL documentation before they start using any software libraries.

I don't expect this, but at least as a user myself, I'll read the documentation on the specific non-trivial function I used, as long as it is not too long and readable.

> If we normalize loginID for uniqueness checking in all login API except one, it is surprising

I'd agree on this if all our APIs are like `loginWithXXX`, where the login ID key is specified. However, personally I wouldn't expect the server to be able to normalize the login ID if the key is not specified, so it would be surprising to me at least.

**Comment by louischan-oursky** [comment]
> Considering the developer can implement it with minimum effort at client side, I don't think it is necessary.

How should the developer implement it? If we do not support this feature natively and mandate login id key to be provided, the developer has to install library to detect the type of the login ID. Most likely they have to install an implementation of RFC 5322 and libphonenumbers and repeat the same logic in every app. I do not want our SDK to depend on these two libraries neither because it largely increases the bundle size.

**Comment by kiootic** [comment]
> How should the developer implement it?

Most apps would NOT use `username` & `email` as login ID key, while allowing using a email as `username` (i.e. the scenario in question). Also, it is unlikely apps would accept arbitrary strings as `username`. Therefore, apps would most likely accept a email as a `email` login ID, and only accept a string in specific format (e.g. alphanumeric string > 8 characters) as `username` login ID. In these cases, simply checking whether the login ID has a `@` character (or conforming to format of username) would suffice.

**Comment by chpapa** [comment]
> Most apps would NOT use `username` & `email` as login ID key, while allowing using a email as `username` (i.e. the scenario in question). Also, it is unlikely apps would accept arbitrary strings as `username`. Therefore, apps would most likely accept a email as a `email` login ID, and only accept a string in specific format (e.g. alphanumeric string > 8 characters) as `username` login ID. In these cases, simply checking whether the login ID has a `@` character (or conforming to format of username) would suffice.

Maybe more common than you think... e.g. Twitter allows both username, email and phone no for login ID. It is very common for consumer software to allow both username (arbitrary strings) and email address to login. The reason is consumer users usually have hard time to remember both their username / email, so it is kind of a trial and error process and consumer software want to minimize the difficulties for users to login.

Maybe users could play smart to use character `@` to detect email address and disallow using email address a-like username, however I think given the use cases is too common (almost any consumer apps that have both username and email address an care about usability would needs it), I think we should still consider doing it...

**Comment by chpapa** [comment]
> I don't expect the user ignores tutorials, documentation website, and auto-complete documentation in editor, then says it's our fault.

> I'd agree on this if all our APIs are like `loginWithXXX`, where the login ID key is specified. However, personally I wouldn't expect the server to be able to normalize the login ID if the key is not specified, so it would be surprising to me at least.

So the logic goes we still should try to avoid hard-to-grab concepts whenever possible...

It could be suprising to you when you know every details in-and-out, but as a designer (no matter it is UI/UX design, or in this case, design of APIs), we need to be able to think in normal user's shoes, and don't assume they have all the knowledge as you do... imagine when you haven't think about the in-and-outs of login KEYs and uniqueness checking, it is actually more "normal" to think the normal `login` function would works similarly with `loginWithXXX` function.

**Comment by kiootic** [comment]
> Maybe more common than you think... e.g. Twitter allows both username, email and phone no for login ID. It is very common for consumer software to allow both username (arbitrary strings) and email address to login. The reason is consumer users usually have hard time to remember both their username / email, so it is kind of a trial and error process and consumer software want to minimize the difficulties for users to login.

I don't see how Twitter is different from what I describe:
- it required alphanumeric + underscore for username
- it allows email as login ID (must have @)
- it allows phone as login ID

The app can do the following:
- if has '@': do login with email
- if has alphabetic character: do login with username
- otherwise: maybe username/phone, can try login with phone, and if failed, login with username
