### ISSUE TITLE
Revisit 'god' user in auth gear

### ISSUE THREAD

**Issue by kiootic** [SkygearIO/features#347]
## Description

In v1, a `_god` user would be associated with records created with master key.

Currently, if user access auth gear API without authentication & with master key, a `_god` user would be created automatically. Since we do not have record gear now, we should re-consider whether this behavior is desirable.

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
@kiootic agree, never liked the hack...

**Comment by kiootic** [comment]
There is no more `_god` user in Skygear.
