### ISSUE TITLE
IoT SDK

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#36]
# Description

Provide basic IoT usage supports. Related repo: 
* https://github.com/skygeario/iot
* https://github.com/skygeario/iot-sdk-js

# Design/Specification

* https://github.com/SkygearIO/features/wiki/Skygear-IoT-Feature-Spec

# Related Issues

**@akiroz please open issues related with this feature and put it below**

- Server Issues
- Client Issues
- Guides Issues SkygearIO/guides#51 SkygearIO/guides#52

# Progress Tracker

- [x] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
@mayyuen318 @akiroz Please put your design here so other team members can look at, discuss and approve.

Please do not add additional features that is NOT absolutely necessary for the 1st version, such as OTA update.

I looked at the mockup design and think the absolute minimal should be:
* Device Presence
* Device Register / De-register
* Meta data support (Device Class)

**Comment by akiroz** [comment]
## IoT Device

* Device String: SoC model + serial number
    A shared secret between the device and the server, used for: username & password
* Device ID: UUID generated on sign-up (user ID)
* `skygearIoT.log(message, attachment)` log to skygear portal (with optional object attachment)
* `skygearIoT.register()` signup using device string & save `iot_device` record
* `skygearIoT.onAction(action, handler)` add an action handler (see details below)
* `skygearIoT.offAction(handlerID)` remove action handler
* `skygearIoT.pubsub.once(event)` subscribe to event once, return promise

## Device Action

IoT device action is a mechanism for pushing tasks to devices that's backed by a privateDB record,
each device can only be assigned one action at a given time.

![diagram1](https://cloud.githubusercontent.com/assets/8231917/24438246/9b06bca4-1478-11e7-93e8-26992281352a.png)

## Public DB

* iot_device
    * _id (skygear user id)
    * class (string)
    * status (online, offline)
    * ip (string)
    * action (string or none)
    * sdk_version (string)
    * app_version (string)

## Private DB

* iot_action
    * action (string)
    * data (optional, object)
    * attachment (optional, asset)
    * status (pending, completed, failed)

## PubSub

* iot-request-renew (for devices)
    published by the server after server restart (e.g. after cloud code update)
    to notify devices to renew access token

* iot-request-action (for devices)
    published by the server when a new record is saved to iot_action
    * data: array of device IDs with pending actions

* iot-request-status (for devices)
    published by the server every X minutes to collect device status reports
    devices should also check for pending actions in case the `iot-request-action` event wasn't received

## Lambda

* iot:action-dispatch (for portal)
    Adds the requested action to the list of devices' iot_action privateDBs
    Requires admin / master key
* iot:log (for device)
    logs message to the skygear portal

**Comment by akiroz** [comment]
@chpapa I'm not sure about device de-registeration, maybe there's just a button in the Skygear Portal to delete `iot_device` records, but the next time you turn on the same device it will just register itself again.

**Comment by chpapa** [comment]
@akiroz Great! Some comments and thought:

1. I think `skygearIoT.pubsub` is not necessary, as there are already `skygear.on` already. Better keep it simple.
2. What is `skygearIoT.log`? Will it create a Record? 
3. `iot-request-renew` is for renewing access token, but does current Skygear auth design require that after server restart? My understanding is no.
4. I would suggest let’s keep the whole iot_action to a separate feature if the only use-case for now updates OTA, which will not be included in the initial release.
5. Should we use privateDB for iot_device?
6. I suggest to add two privateDB:
- iot_device_login_history
  - device_id
  - ip
  - sdk_version
  - app_version
  - timestamp
- iot_device_alive
  - device_id
  - ip
  - timestamp
7. `iot_device_login_history` should replace the relevant attributes in iot_device.
8. I think for `skygearIoT.register`, it will need to collect device class / app_version? (or device class is set from server side?)
9. How does the `iot_device.status` attribute updated?

**Comment by akiroz** [comment]
1. I ended up having to use the `once` helper function quite a lot when writing in ES7 async style so I'm thinking of providing it as a util function.
2. It's directly wrapping around a lambda, currently I plan on dumping to STDERR on the server.
3. I remember none of my client requests apps were working after I update cloudcode in a previous project, need clarification.
4. the action mechanism is designed for users since there's no way to push tasks to specific devices and make sure it will be done (but update system will also use it)
5. this is somewhat global data, maybe set the ACL to no access by default?
6-7. but then the portal page will have to query every device's private DB on load.....
8. there's a private method in the SDK called _reportStatus to save a `iot_device` record, the register function will call it after logging-in. App version is client-side (read from `package.json`) but device class is server-side.
9. when the device reports its status, it will also set the status to online, I'm thinking that the server should set it to offline after some amount of time without receiving status reports.

**Comment by chpapa** [comment]
1. If that's true it should belongs to the https://github.com/skygeario/skygear-sdk-js, agree?
2. okay.
3. Maybe it is better to auto-sign again if the token is not valid anymore? It should be a more general solution? (I think access token need to renew if using FS / Redis sessions tore)
4. Do you agree it would be more elegant if we just have #35 Cache pubsub for offline device, instead of adding a new "action" thing?
5-7. PrivateDB of different users are in the same table XD You're right maybe conceptually it is better to have publicDB but set ACL to no public read by default.
8. ok
9. Agree. Actually I'm thinking maybe we should remove `iot_device.status` (or just leave it there as a cache), instead, we can determine if a device is online / offline by:
  a. Timeout from `iot_device_alive`
  b. Have an explicit `skygearIoT.offline()` call and marked in in DB.

**Comment by akiroz** [comment]
1. oh sure

3. Hmm... I'm thinking if it's safe to the renew the token everytime I get an access error...

4. but if I use pubsub, any user will be able to send tasks to any device

5. wow, I didn't know that :o

7. yeah, I think that will work. In the dashboard, if the latest `iot_device_alive` record is older than X then display it as offline.  If we do (b) as well, we could have an extra column to explicitly say it went offline.

**Comment by chpapa** [comment]
3. I think it is okay. Just make sure you catch the correct error, and we're using HTTPS. (looks at https://github.com/SkygearIO/skygear-server/blob/master/pkg/server/skyerr/skyerr.go, it should be AccessTokenNotAccepted, maybe you can check)

4. Each device should have a sufficiently long channel name to communicate with the Skygear Server (ex. access token? or HMAC(access token)?)

If these are settled may you update all the design specification in the issue description? Than we should be specification completed! XD

**Comment by akiroz** [comment]
Awesome, looks good to me.

**Comment by akiroz** [comment]
@chpapa I've just updated the design spec, please have a look~

**Comment by chpapa** [comment]
@akiroz As spoken today, may you revisit the interface of IoT SDK so it is more usable (not just usable by RPi image), and update the design spec here?

**Comment by mayyuen318** [comment]
@akiroz @chpapa if you two have come to a conclusion after discussion. Boris could you write down what you are going to do for documentation?

**Comment by akiroz** [comment]
@mayyuen318 The specification for our SDK is in this github wiki page: https://github.com/SkygearIO/features/wiki/Skygear-IoT

**Comment by chpapa** [comment]
I have put it on description too.

**Comment by chpapa** [comment]
@akiroz Running through some other idea, do you think you can revise it in minimal?

1. Revise `skygearIoT.initialize(platform)` into:

`skygearIoT.updateDeviceInfo(platform)` or
`skygearIoT.updateDeviceInfo(shutdown, restart, deviceSecret, appVersion)`

Rational: initialize imply initialization of the skygearIoT object, however it is supplying info for each login session. So call it updateDeviceInfo would be better.

2. `skygearIoT.reportStatus()` can we change it to `skygearIoT.reportStatus(metaData)`? seems it would be useful and handy for providing some serialized data.

3. Can we change `skygearIoT.log(message, attachment)` to something like these?

`console.error()/info()/.log()/warn()`

Reference: https://nodejs.org/api/console.html

It is to make it consistent and familiar with the normal log JS users would use. And also it is better to have the correct log level on Skygear Server.

**Comment by akiroz** [comment]
1. right now `initialize` does these things:
    1. set device info & generate pubsub channel hash.
    2. if user is not an `iot-device`, set it and save the `iot_device` record.
    3. save the `iot_device_login` record
    4. register pubsub hooks
2. sure, I'll add an extra column to the status table.
3. ok, I'll just create `skygearIoT.console` which internally pipes all output back to the server.

**Comment by chpapa** [comment]
1. What about `initDevice` than? So at least doesn't sounds like init the skygearIoT object :) Or any better name you have?

**Comment by akiroz** [comment]
Sounds good to me~ I'll update the spec then.

**Comment by chpapa** [comment]
@akiroz @rickmak @mayyuen318 I have marked this issue as design complete. Despite @akiroz got a few minor things to update.

@akiroz can you put all the remaining issues on the description of the issues?

**Comment by chpapa** [comment]
Also be noted about the Progress Tracker, here are the next milestone to complete this feature:

Write (code + tests + API docs) then get them merged. Put All PR there
- Code
- Minimal tests
- Minimal API Docs

**Comment by akiroz** [comment]
@chpapa 
Updated Spec: https://github.com/SkygearIO/features/wiki/Skygear-IoT-Feature-Spec
API Doc: https://doc.esdoc.org/github.com/SkygearIO/iot-SDK-JS/

**Comment by cheungpat** [comment]
I just noticed that there is a feature request to show data from skygear server database in the portal. I would like to know more about how this will be implemented? (how will the portal be able to access data in the app’s skygear database?)

**Comment by rickmak** [comment]
I regard​ this feature is approved and completed?
