### ISSUE TITLE
Review tenant config and set principles 

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/features#368]
## Description

**Add 2-3 sentence description of your feature**

## Portal Design

**Remove this section if the feature have no Portal**

## Blog Post Specification

**Blog Post of the Feature Release**

## Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by carmenlau** [comment]
@louischan-oursky @kiootic @chpapa For the tenant config change that we discussed in the product meeting, I drafted some points and added the example config. Please kindly take a look and let me know your thoughts. I will add this to the spec when we have consensus!

## Should use array or map to define dynamic items in user config?

- Map with identifier as key
    - Pros:
        - Clearer for referencing (e.g. configure user verification need to refs items in login id keys)
        - Prevent duplicate key by config structure
    - Cons:
        - The config looks inconsistent. For items that we don't have identifier, we use array. (e.g. In id in sso provider is optional. If it is not provided, we use type as the id. sso providers is array now).
        - Cannot preserve item order
    - Existing config that use map
        - docker compose config defines volumes and services
        - aws cloudformation defines resources
- Array
    - Pros:
        - Can represent all items (with or without identifier)
        - Can preserve order
    - Cons:
        - Need validation to prevent duplication
    - Existing config that use array
        - k8s resources spec

I prefer using array to prevent inconsistent.

## Should we have `enabled` config

We should only have the `enabled` for enabling feature. Config file should not be a place that store the config data temporarily. We should not add `enabled` or `disabled` flag to item, instead user should delete the item if they don't need it. In most of the common platform (gcp, aws.. e.g), we don't often see disable an item option in their portal. User has responsibility to keep the copy of the config, to make it simple, ui should only support adding or removing items.

## Config updates

- Remove `disabled` in `clients`
- Change all map to array. (e.g. clients, auth.login_id_keys, user_verification.login_id_keys)
- Rename `id` in sso provider to `name` as it is optional?

## Portal remarks

Portal should handle editing config that affects multiple sections. For example, remove login id key should also remove the user verification config if the id is enabled in user verification section. Maybe adding warning in ui, before deleting a login id?

## Config example

Based on the proposal, here are the config for preview.

Current user config example (https://github.com/SkygearIO/skygear-server/commit/ba7713cd6555892b4de5952bfc58d8f05bf8baa3) :  https://gist.github.com/carmenlau/f88174da774a502caad9d3140eab1cd4

Updated user config example: https://gist.github.com/carmenlau/154f53db4812a5cfe9fbe12baff86ce0

**Comment by kiootic** [comment]
list/map: I think we can refer to [k8s's convention](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps) on this. Personally I do think k8s has a good API design.

enabled config: A disabled config would be required if a disabled item and a removed item would have noticeable behavior difference. However, existing disabled flag would behave same as being removed, so I think we can remove this config for now.

**Comment by chpapa** [comment]
I love the way @kiootic point out k8s's convetion and its discussion, we should do more of these in different difficult questions -- as long as we are consistent that will help us save a lot of time :)

Another aspect is, since Skygear is based on k8s, a lot of our users would definitely come from similar background, making our config convention identical with k8s help user familiar with us quickly.

> Portal should handle editing config that affects multiple sections. For example, remove login id key should also remove the user verification config if the id is enabled in user verification section. Maybe adding warning in ui, before deleting a login id?

Sounds good. I guess we will repeat the mistakes of AWS Console -- I still remember AWS console would crash / malfunctions in the early dates a lot when a referencing objects is removed. Maybe we need to set up some pattern in code-level of portal, so that when some references is removed, it won't crash and provide a sensible side-effect.

**Comment by carmenlau** [comment]
Thanks @kiootic :) That's really a good reference for us. I created a basic version of config conventions spec as a starting point (#371). See anything else we should cover? And we can further enrich the document if we face the similar problem.
