### ISSUE TITLE
Pubsub Dashboard

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#37]
# Description

A Dashboard to listen to Pubsub Channel, and send Pubsub message via Portal

# Design/Specification

**Design Link:** https://projects.invisionapp.com/share/6AB1RERBK#/screens/225937760

#### Publish part 
* If the users click “Publish” without subscribing a channel (i.e. disconnecting status), a red line under the message textbox “Please subscribe a channel first” should be shown.
* If the users click “Publish” with an empty message box, a red line under the message textbox “Please enter your message” should be shown.
* If the users successfully publish a message, a line with a timestamp, publish channel and message content will be shown in the log.

#### Subscribe part 
_Input part_ 
* If the users click into this page with no subscribed channel, under the Subscribe Message Log it should say “Subscribe a Channel to Display the Log” in a prominent colour (Red)
* Users click at 'Subscribe' button to subscribe a channel. If the channel is empty, a red line should be displayed under the textbox “Channel name is needed”; If the subscription was succeeded, the status icon should change to green with the word “Connected”. 
* The status icon of connecting status should be in yellow color with the word 'connecting'.
* The connecting timeout will be 3 seconds.
* After users successfully subscribe a channel, the Subscribe Message Log should state: 'No message is loaded'
* The status icon should change according to the connection status of subscription.
* When the status is connected, the button 'Subscribe' will become button 'Unsubscribe' for users to disconnect the subscription.
* If users click the 'View the Pub/Sub' from IoT Device List table, they will be redirected to Pub/Sub page and subscribe the relevant channel automatically.

### Message Log
* After subscribed to a channel, all new pubsub messages should display in text under Subscribe Message Log.
* The Log will be inverse-log. The latest message will be shown at the top.
* The displayed information should include (Boris please help fill this)
* If there is any pub/sub state change, we will display a read line in the Message Log. 'Subscribed a channelName at when' and 'Unsubcribed a channelName at when'
* All logs relevant to publish event will be in blue color
* All logs relevant to subscribe event will be in grey color

### Things shown on the Subscribe Message Log:
* Timestamp
* Channel
* Message

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [x] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should go in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by rickmak** [comment]
The usage cover well on disconnect -> connect transition.

Missed connected -> disconnected transition.

- What happen to the input box and the `subscribe` button at channel after it subscribed? I suppose the input will become disable and button become `unsubscribe`.
- I suggest the newest message appear at top and save the effort to `scroll` to bottom.
- Put the connection state near the message.
- Will we have state change indicator at the message panel? i.e. a read line represent the pub/sub is disconnected at a specified time.

**Comment by mayyuen318** [comment]
Thank you @rickmak for the professional advice! Much appreciate.
I have updated the spec accordingly.

In the meantime, Boris strongly advise To separate the publish and subscription part. I will work with Siutao and Boris to update the design.
Later all, the top part will be publish and the bottom part will be subscription + log. 
I will update everyone here once the design completed
