### ISSUE TITLE
Static Website Hosting

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#375]
## Description

Support hosting a directory of static website on Skygear Cloud directly with CDN automatically configurated.

We have designed part of the static asset support in [CF spec]( https://github.com/SkygearIO/features/blob/master/features/268-next-cf). When we start designing the static asset spec, we can take it as reference, create a new spec and remove the irrelevant parts.

## Portal Design

* List all deployment of static website
* Configurate Custom Domain name for each deployment

## Blog Post Specification

**Blog Post of the Feature Release**

## Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
    - SkygearIO/skygear-server#1201
- Client Issues
- Guides Issues

**Comment by hidden-dimensions** [comment]
When we do it, will it also support react url routing?

**Comment by chpapa** [comment]
> When we do it, will it also support react url routing?

Not entirely sure what that's? Mind explain more? @hidden-dimensions

**Comment by chpapa** [comment]
@louischan-oursky is it closed accidentally? We haven't implemented it nor have the guides updated yet?

**Comment by louischan-oursky** [comment]
Sorry, I merged the feature spec PR and this issue got accidentally closed because the PR description has a `fix` keyword.

**Comment by kiootic** [comment]
For reference, on GCP:

First 5 forwarding rules (i.e. load balancer): $0.025 / hour
Each additional forwarding rule: $0.01 / hour

Load balancer ingress: $0.008 / GB
CDN cache lookup: $0.0075 / 10000 requests
Non-cached content egress: $0.08 - $0.12 / GB
CDN cached content egress: $0.02 - $0.20 / GB
CDN cache fill: $0.04 - $0.15 / GB

**Comment by chpapa** [comment]
@kiootic any explaination of how that pricing applies to us for additional cost for each custom domain? (Ignore the bandwidth first)

**Comment by kiootic** [comment]
If ignoring ingress/egress traffic, the only cost is the forwarding rules. Therefore, each custom domain would cost ~ $0.00066 per hour (0.01 / 15).

Also for reference:
SSL certificates per proxy (i.e. load balancer): 15 (cannot be increased)
Forwarding rules (i.e. load balancer): 45
