### ISSUE TITLE
Device List at Portal

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#38]
# Description

Allow users to look at a list of devices registered via SDK.

# Design/Specification

### Usage

* Users can view all the device status, device information and set remote action for the device on the device list
* This feature is optional. Users turn this feature on when needed. 

Design Link: https://projects.invisionapp.com/share/6AB1RERBK#/screens/225932555

### Device List:

| Status |	Device ID | Device Class | IP Address | Device Channel | Skygear SDK Version | Application Version |
|---|---|---|---|---|---|---|
| **grey:** offline **green:** online| String (provided by IoT SDK)| String (server side setting)| String | View in Pub/Sub (link)| String | String |

Users can perform 3 things in this table. They can 

1. Filter information to view the table
2. Multi-select the device to perform 3 actions
3. Click the 'View in Pub/Sub' link in Device Channel on the table for Pub/Sub feature

**1 - Filter information to view the table**

There are filter for the table. If multiple conditions are selected, it is consider an AND conditions.

* IP address - filter by sub-net (e.g. 192.168.0.0/16)
* Device Class - use drop down 
* Device ID - exact match match substring
* Skygear SDK version / Application version 
  - Placeholder will educate the users to use standard format (semver) 

**2 -  Multi-select the device and perform 3 actions**
The multi-select function is on the first column of the table.

The 3 actions are

* Restart Device - multi-select
    * confirm button on a pop-up
* Shutdown Device - multi-select
    * confirm button on a pop-up
* Set Device Class - multi-select
    * text input, auto-complete with existing device classes.
    * confirm button on a pop-up

When there is no check off on the box, the 3 actions buttons should be unclickable.  

**3 - Click the 'View in Pub/Sub' link in Device Channel on the table for Pub/Sub feature**
When users click on the 'View in Pub/Sub' link, they will be redirected to the Pub/Sub dashboard page with the param (the subscribe channel)  

# Related Issues

- Server Issues
- Client Issues
- Guides Issues
- Depend on #36 IoT SDK

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
@mayyuen318 Please put the mockup design / interactive prototype here, after it was done by business and design team.

**Comment by chpapa** [comment]
@mayyuen318 Do we have the design of device list finalized? If yes can you put it up on description?

**Comment by rickmak** [comment]
> IP address - filter by sub-net (e.g. 192.168.0.0/16)
I am a bit concern is this syntax... we need to tell the user we accept only inet syntax.

> Device Class - exact match with lower case, match english characters and numbers only
> Device ID - match substring
At UI, there no hits on it is matching exact or substring.

> Skygear SDK version / Application version - exact match
Exact match mean minor version? Exact match might not useful. gt/lt match seem make more sense.

**Comment by chpapa** [comment]
> I am a bit concern is this syntax... we need to tell the user we accept only inet syntax.

I think it is fine, as long as we have a placeholder. There is no other popular format I'm aware of?

> At UI, there no hits on it is matching exact or substring.

what about turns device class into dropdown? Or auto-complete.

Or actually we can leave the whole filter button out in the first phase.

**Comment by rickmak** [comment]
> I think it is fine, as long as we have a placeholder. There is no other popular format I'm aware of?

A placeholder will tell the user which format. And for good UX, we may need to tell the user the format is wrong interactively.

My concern will be the use-case, not sure the IP is private IP or public IP. I guess in real world IoT don't have a real IPv4, not even `/30`? At the end, users may want to match the private IP as a string for fast check of devices? I don't have much knowledge on how IoT device is deployed. Just guess.

**Comment by chpapa** [comment]
Maybe not a must for phase 1. I think it depends on what kind of deployment.

**Comment by mayyuen318** [comment]
@akiroz let me know your thoughts.

Could we separate it into 2 phrases? Could we cut the filter part at the 1st stage? 
For the filter session, we need to further discuss with Siutao about how to display the UI regarding the issues @rickmak raised up above. 

cc @chpapa

**Comment by mayyuen318** [comment]
After talking with @akiroz, I have updated the design spec of the filter section. 

- Device Class  (will use drop down instead of input)
- Device ID - exact match substring
- Skygear SDK version / Application version 
   - Placeholder will educate the users to use standard format (semver) 

For filtering by IP, do you two @chpapa @rickmak have the conclusion about what format we should use?? Would love to update the spec and maybe design as well.

**Comment by chpapa** [comment]
> For filtering by IP, do you two @chpapa @rickmak have the conclusion about what format we should use?? Would love to update the spec and maybe design as well.

The conclusion is it is best to make the box works in both ways:
* If user input a CIDR notation (e.g. 192.168.1.0/24), we filter by subnet
* If user input anything else, it is a sub string search.

But this is optional for phase 1.
