### ISSUE TITLE
Sign in with Apple

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#380]
## Description

Support Sign in With Apple

## Portal Design

* Configurate it on Portal

## Blog Post Specification

**Blog Post of the Feature Release**

## Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
  - [x] https://github.com/SkygearIO/skygear-server/issues/1117
- Client Issues
  - [x] https://github.com/SkygearIO/skygear-SDK-JS/issues/547
- Portal issues
  - [x] https://github.com/oursky/skygear-next-portal/issues/158
- Guides Issues
  - [x] https://github.com/SkygearIO/guides/issues/264

**Comment by louischan-oursky** [comment]
I spent an hour researching Sign in with Apple.

## Hide my email

The user can choose to hide their real email. Apple then generates an email address for them. If the user chooses to do so and we want to send email to that email address, we have to follow [this setup](https://developer.apple.com/documentation/signinwithapplejs/communicating_using_the_private_email_relay_service)

## Check credential state on iOS app launch

The user can revoke their access anytime they want. The iOS application must check whether the access is revoked. If yes, the application should log the user out. This means a fully integrated experience requires native Skygear iOS SDK.

## Listen to ASAuthorizationAppleIDProviderCredentialsRevoked

Again this require native SDK.

## Integration on other platforms

Integration on other platforms require the use of Sign in with Apple JS. It is the official JS SDK. The integration should be a webpage with the Sign in with Apple JS included. We can serve such webpage with Auth Gear. However, the developer may want to customize it.

## Backend integration

This should be pretty standard. The client submit the credentials to Auth Gear. Auth Gear then validate the given credentials with Apple REST API.
