### ISSUE TITLE
Use policy-based ACL

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#39]
# Description

Extend ACL to policy-based for fine-grained access control, with sensible default for users like role-based one.

# Questions

* Can we use some opensource project like https://github.com/ory/ladon for the ACL server?

# Design/Specification

Some notes for ideas:
* An policy-based ACL define **Who** can do **What** on **Resource**
  * Who - Users / Role as in existing Skygear
  * What - READ/WRITE/CREATE/DELETE
  * Resource: records: `<record type>:<record id>:<column name>`
* Check all queries against an ACL policies service, when constructing the query to say "yes/no" for certain query, and limits the columns retrieved.
* Sensible default, so users can simply say: **User A/Role A can READ all RECORDS A** with a few set of default policy, to avoid developers have to mess with policy file all the time.

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
An alternative to ladon

**Comment by chpapa** [comment]
An alternative to Ladon: https://github.com/hsluoyz/casbin

**Comment by hsluoyz** [comment]
FYI, casbin has moved to a more official place: https://github.com/casbin/casbin

And for your consideration, I compared casbin with ladon about the differences:
1. Ladon doesn't support advanced models like RBAC, ABAC, although it mentioned RBAC in README, but it's not there in the code. Casbin supports models like RBAC, ABAC.
2. Ladon imports [three 3rd-party libs](https://godoc.org/github.com/ory/ladon?imports), beyond that another dependency for test is github.com/stretchr/testify. While casbin only [imports one 3rd-party lib](https://godoc.org/github.com/casbin/casbin?imports).
3. Ladon's policy is JSON and seems to be a little complex. casbin's policy is in CSV. While, I don't know if it's a good thing. If you prefer JSON, casbin can support JSON too:)
4. Ladon seems to have 5+ unresolved issues. Casbin should be more responsive than that. And I'm usually ready to provide help for the users.

Thanks!
