### ISSUE TITLE
OIDC flow support prompt=login

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/features#439]
## Description

**Add 2-3 sentence description of your feature**

## Portal Design

**Remove this section if the feature have no Portal**

## Blog Post Specification

**Blog Post of the Feature Release**

## Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

**Comment by chpapa** [comment]
I think it is prompt=login, typo?

**Comment by carmenlau** [comment]
Yes, updated :P
