### ISSUE TITLE
Support revision history and versioning on CMS

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#44]
# Description

Support versioning of content in CMS. So that end users can rollback in case a wrong content is updated.

# Design/Specification

**Put Design and Specification here with links**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by rickmak** [comment]
Should we escalate this feature to support versioning in Record core?

**Comment by chpapa** [comment]
> Should we escalate this feature to support versioning in Record core?

Hmmm, I don't think so, I would prefer we make it a "convention" of how records should store for versioning. And maybe provide some util functions in SDK for accessing them.

Having said that, I personally don't really like these features, but I'm open to implementing them if there are strong business needs.
