### ISSUE TITLE
Research for an better transport between Skygear-server and Plugins runtime

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#47]
# Description

This is an issue to evaluate the usage of HTTP2 and [Message Pack](http://msgpack.org/) as transport between Skygear-server and plugins runtime in Skygear micro-services architecture.

It aims at replacing zmq for maintainability.

# Design/Specification

**Put Design and Specification here with links**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by cheungpat** [comment]
I am neutral to using HTTP/2 and MessagePack per se, but I think we should also consider using a RPC protocol/library rather than rolling our own if it makes sense.

**Comment by chpapa** [comment]
@cheungpat I agree!!!!! 

@rickmak mentioned these so I put it on title. But I think it might worth spend some time to do a more detail evaluation and decide what to use.

**Comment by seventhmoon** [comment]
If only looking for an alternative for JSON with smaller size, why not protobuf or flatbuffers?

**Comment by chpapa** [comment]
> If only looking for an alternative for JSON with smaller size, why not protobuf or flatbuffers?

Actually, we don't really have a decision yet. But we kind of agreed zmq maybe overkill and alternatives might be easier to maintain. So whether we would have a new transport protocol (HTTP2?) / A more efficient format compare with JSON / use an RPC library (gRPC?) is up for evaluation.
