### ISSUE TITLE
Disable users

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#50]
# Description

There are cases to temporary disable a user. For example, violation of the term of use; awaiting settle of a payment, etc.

Currently, a developer can do two things to achieve the goal.
1. Change the password of the user. (Usually add a `!` in front of the password has to make it invalid)
2. Mark the user as disabled at `user` record.

We want to provide a built-in way to do it.

# CMS Design

## CMS Features

- A button to disable a user temporarily, with these parameters:
  - disable until Date Time (Time Zone)
  - A message to display when the user tries to login again
- A button to enable the user back
- A button to "Require user to change password in next login"

## UX Design
**Put (link to) Portal Design here**

# API Design

### APIs

These three API requires a special "user_management" role to call:
* `skygear.auth.disableUser(user, [message="Account blocked"], [expire_at=never])`
* `skygear.auth.enableUser(user)`
* `skygear.auth.changePasswordatLogin(user)`

After `disableUser` or `changePasswordatLogin` was called, the user's subsequent API call will return `NotAuthenticated`.

### Server Design

* skygear-server provider after user login hooks, and plugins listen to the hooks to block user login
* have a simple boolean variable at _user or UserProfile(which is better?) to define blocking status

## Scenario

**Put list of Scenario how developers will use this API**

## Sample Code

**Put sample code of how you vision this API will be used, consider different type of developers and different abstract level**

# Open Questions

* Should we return NotAuthenticated for blocked users, or better another error code that's for the exact purpose?

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
@rickmak I closed your issue #116 since we already have an old issue here.

I notice in #116 you have mention forgotPassword, I guess that's not related?

**Comment by rickmak** [comment]
Forgot password is one way that existing implementation uses to re-enable the user account. Thus, it is recovering disabled account by reset password.

Just a side note, we can ignore it if we provide a dedicate way/API to recover a user account.

**Comment by chpapa** [comment]
@rickmak Ic. I guess the above mechanism for re-enable a blocked account is good enough?

1. Manually enable from user management list
2. Disable until a date / time

Maybe we can add another feature is "require change of password in next login" for those who want to intentionally force users to change password before continue using the account.

**Comment by cheungpat** [comment]
I noticed that this issue mention the “require change password for next login” kind of use case, which i think is orthogonal to the “disabled user account” use case.

If the “require change password for next login” use case is required, I’d suggest writing another issue spec for this, because: a “require change” account is not the same as a disabled account, a “require change” account is not necessarily disabled.

**Comment by chpapa** [comment]
> If the “require change password for next login” use case is required, I’d suggest writing another issue spec for this, because: a “require change” account is not the same as a disabled account, a “require change” account is not necessarily disabled.

There are two types of "change password for next login":
1. disable an account, and force change of password in next login to enable it again.
1. suggest / force change of password at next login but don't disable the account.

I think @cheungpat is referring to 2nd one, which could/should be done by users developer in Cloud Functions.

However for 1st one, it will be closely related with this issue of disable account and probably can't be done by users developers (since any API call to disabled users should trigger error even resetPassword).

**Comment by chpapa** [comment]
@carmenlau I'm re-opening this as this feature obviously need update on guides, but I don't see any records of it have been done?

**Comment by carmenlau** [comment]
Yes, it is not done yet I should not close the issue. Just opened related guides issues in case we forget. thanks

**Comment by carmenlau** [comment]
Disable user guide: https://docs.skygear.io/guides/auth/disable/ios/
