### ISSUE TITLE
Create guides for integrate JS SDK with various framework

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/features#52]
# Description
Create guides for installation of Angular2 / Ionic 2 / React.js; And boilerplate for React Native.

Decide a guide for browsify / webpack depends on popularity.

# Related Issues

- Code
  - SkygearIO/skygear-SDK-JS#160
- Guides
  - SkygearIO/guides#58
- Boilerplate
  - React Native Boilerplate

# Progress Tracker

- [x] Guides. **Put All PR there**
- [x] Release
  - [ ] Update release notes
  - [ ] Release

**Comment by seventhmoon** [comment]
I think you mean Angular (v4).
