### ISSUE TITLE
Add descriptions for API reference

### ISSUE THREAD

**Issue by mayyuen318** [SkygearIO/features#54]
Since JS SDK have **no auto-completion** like iOS / Android, the option fields and return types on documentation are relatively important for developers to do implementations. This issue would like to complete some of the descriptions of the API references that are frequently used by other developers.

Aiming to at least filling those **input param, option fields & return types** for those frequently used APIs. It would be great if we can add example there. 

### Auth
(I am not sure the difference between two. Not sure if both are under Auth. Correct me if I am wrong)
- [AuthContainer](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/auth.js~AuthContainer.html)
- [BaseAuthProvider](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/cloud/index.js~BaseAuthProvider.html)

### Datebase & Query
- [ACL](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/acl.js~ACL.html)
- [Asset](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/asset.js~Asset.html)
- [Cache](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/cache.js~Cache.html)
- [Datebase](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/database.js~Database.html)
- [Query](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/query.js~Query.html)
- [QueryResult](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/query_result.js~QueryResult.html)
- [Record](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/record.js~Record.html)

### User
- [User](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/user.js~User.html)

### Functions
- [event](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/function/index.html#static-function-event)
- [every](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/function/index.html#static-function-every)
- [staticAssetHandler](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/function/index.html#static-function-staticAssetHandler)
- [hook](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/function/index.html#static-function-hook)
- [op](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/function/index.html#static-function-op)

### Others
- [SkygearError](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/error.js~SkygearError.html)
- [EventHandle](https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/packages/skygear-core/lib/util.js~EventHandle.html)

Plus giving a general description for all classes

**Comment by chpapa** [comment]
Shall we close this if we are not doing anything active here...? @carmenlau

**Comment by carmenlau** [comment]
Sure
