### ISSUE TITLE
Sign in with Custom Token

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/features#56]
# Description
Similar to firebase.auth().signInWithCustomToken(token), which allow custom integration on other sign-in services.

# Portal Features
* Enable/Disable Custom Token function in Portal
* Generate / Download Key for client's App Server to generate JWT Token

# API Design
* Client SDK: Similar to firebase.auth().signInWithCustomToken(token)
* Consider comply with OpenID Connect JWT Spec?
  * Check `iss` and `sub` to match with the project's name
  * Check `aud` match with Skygear
  * Check `exp` is not expired
  * Use `uid` for user id?
  * Use custom claims to populate claims value in User Profile (?)

# Guides Required
* [ ] API Reference (iOS/JS/Android): for Client SDK
* [ ] Guide (iOS/JS/Android): Authenticate with Custom Authentication System
* [ ] Guide: Create Custom Token [Ref](https://firebase.google.com/docs/auth/admin/create-custom-tokens), provide recommend 3rd party library and sample codes for common languages.

# Scenario
Integrate with their apps' own authentication server.

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
@b123400 Can you also look at this feature issue and see if it is related with #5 which you're working on? cc: @rickmak

**Comment by seventhmoon** [comment]
It is close, but seems not the same.
https://firebase.google.com/docs/auth/web/custom-auth
https://github.com/firebase/functions-samples/tree/master/linkedin-auth

Or #5 is mean using cloud functions to do this kind of thing?

**Comment by chpapa** [comment]
Yea it is different.

#5 is probably meant to use AuthProvider of Cloud Functions to implement a plugins which support common SSO providers. (https://github.com/SkygearIO/py-skygear/blob/master/skygear/providers.py)

CustomToken seems really useful to integrate with anything that's custom and support JWT already. I imagine we would need the following to implement this:

1. Implement a CustomAuthProvider extends BaseAuthProvider
2. Implement the relevant functions in JS / iOS / Android client SDK
3. Provide some standard token generation for server side languages (or like Layer documentation, basically point it to some open source libraries)

BTW, Layer have a similar implementation too: https://docs.layer.com/sdk/web/authentication

Thoughts?

cc: @rickmak

**Comment by rickmak** [comment]
Current BaseAuthProvider design can easily extend to support API like `CustomAuthProvider`.

> Provide some standard token generation for server side languages (or like Layer documentation, basically point it to some open source libraries)

I think providing a `createCustomToken` method in cloud code SDK will be more convenience.

**Comment by chpapa** [comment]
> Current BaseAuthProvider design can easily extend to support API like CustomAuthProvider.

Agree, I think this is the way to go. Should be easy.

> I think providing a createCustomToken method in cloud code SDK will be more convenience.

I think this is different things -- the token generation will not be run on Cloud Code SDK probably, it will be something independent and run at 3rd parties server. Actually, we don't have to do it if we replicate how layer do it -- they basically support JWT and point to sample code / JWT open sources implementation.

**Comment by rickmak** [comment]
> it will be something independent and run at 3rd parties server

I think they can install the py-skygear/skygear-node to their servers.

It is how firebase does. They have a package call `firebase-admin`. It is handy and required the less knowledge from the developer.

**Comment by chpapa** [comment]
> I think they can install the py-skygear/skygear-node to their servers.
> 
> It is how firebase does. They have a package call firebase-admin. It is handy and required the less knowledge from the developer.

Would it be overloading skygear-node too much? firebase-admin is an independent SDK. (And it is not just Javascript, it have Python and Java too)

Would have to see how common those cases are before we invest another set of libraries just for 3rd party server auth I guess.

**Comment by b123400** [comment]
I never used this auth mechanism, but just by reading the doc, seems like an important goal is to avoid sending username/password to the service (Skygear/Firebase/Layer). I guess maybe because some companies don't want to pass auth data to a server they don't own. If we implement it with AuthProvider, username and password have to go through skygear-server and that's not very good?

**Comment by chpapa** [comment]
@carmenlau per our discussion, Firebase actually have a pretty good layman explanation of creating JWT token for custom sign in:

https://firebase.google.com/docs/auth/web/custom-auth
https://firebase.google.com/products/

**Comment by carmenlau** [comment]
Released in v1.3.1
