### ISSUE TITLE
Providing Polymer WebComponent like PolymerFire do

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/features#57]
# Description
I think providing a web component on polymer like [polymerfire](https://www.webcomponents.org/element/firebase/polymerfire) could help lower the barrier for developer.

## Sample Code
I started something, but not yet completed. (as a Lvl 0 JS developer)
https://github.com/astri-isns/polymersky
https://github.com/astri-isns/polymersky-sample

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
@seventhmoon great idea! definitely, let us know how we might help?

**Comment by rickmak** [comment]
A repo is created for this purpose: https://github.com/skygeario/polymersky
