### ISSUE TITLE
Features design doc should goes into repo

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/features#61]
# Description

This issue is not exactly a skygear-server feature request but about how the feature repo can work better.

I am suggesting that feature design documentation should go into the repo, for the following reasons:

* Documentation is easier to find even after the issue containing the original discussion has been closed.
* Document contains the final version of the draft. Currently we have to look into the entire discussion thread on an issue to understand what goes into the final design and ultimately the implementation.
* Changes to design doc can goes through the github flow, meaning that drafts are created by pull request and iterated by commenting on the pull request. The changes are accepted when the pull request is merged.
  * It is easier to comment on document in a pull request than in a discussion thread (always have to copy lines into comment field to refer to a specific point). GitHub pull request review is much easier.

## Scenario

Here is how I envision the flow should go:

1. Open new issue for feature request (existing)
1. Discussion on the feature request (existing)
1. Make early draft on the feature in the issue (existing)
1. Further comment on the draft in the issue (existing)
1. Create a new pull request with the final draft (new)
1. Further commenting on the final draft on pull request (new)
1. Pull request is merged to master when the draft is accepted (new)
1. Update the feature issue with issues for implementing the feature (existing)

# Open Questions

* I hope this won’t make more work for everyone. 
* On the other hand, it makes it easier for people to comment on draft.

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [x] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
I think it is a good idea.

**Comment by tensiuyan** [comment]
I think we can start this with Facebook and Google login implementation #5.

**Comment by chpapa** [comment]
I would suggest the following folder structure:

* /features/[issue num]-[feature name]/
  * /features/[issue num]-[feature name]/portal
    * /features/[issue num]-[feature name]/portal/[design files*]
  * /features/[issue num]-[feature name]/api.md

e.g. /features/61-features-design-doc/api.md

Have a `/api-template.md` with the following content:

```
# API Design Overview

# Sample Codes for Use Cases

# Changes on SDK

# Changes on API at skygear-server

# Changes on Lambda Functions

# Database Scheme

# Others Supplement Information
```

ISSUE_TEMPLATE.md should be changed as well:
* Remove sub-heading UX Design, Sample Code and API Design
* Need to add links to the repo's files on the issue?

**Comment by cheungpat** [comment]
I think this is a good idea.
