### ISSUE TITLE
Support offline message cache and sync for Chat

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#64]
# Description

* Sync current users' participated conversation message history. When enabled:
  * it works with API like getMessages / getConversations to make sure function return cached messages/conversations
      * it provides callbacks to user' code for these events: `unsynced`, `syncing`, `sync completed`, `error` etc.
      * it listens to events and updates the Messages/Conversations local cache in real-time.
      * it auto-download and cache files in Messages if criteria met (criteria includes max size, MIME types, and if auto-download is enabled)
      * it auto-cache user records in message / conversations
  * it supports offline create conversations/send messages/change participants etc
      * it provides callbacks to user' code for send message success, failed, and a way to retry.
* It should also work with the iOS and Android UIKit

# API Design

# Related Issues

- Server Issues
- Client Issues
    - Fill in: JS SDK related issues
    - Other SDK remaining bugs / test
- Guides Issues

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by Steven-Chan** [comment]
# WIP

## SDK API interface

*The following code is pseudo-code only.*

### `Cache`

```
set(message: CachableMessage, forKey: string) -> boolean
get(messageForKey: string) -> CachableMessage
purge(key: string) -> boolean
purgeAll() -> boolean
```

(possible) implementation, each of them would provide individual set of configuration:
- `MemoryCache`
- `LocalStorageCache` (js)
- `RealmCache` (android/ios)
- `CoreDataCache` (ios)
- `SQLiteCache` (android)

### `CachableMessage<T>`

```
- text -> string
- data -> T
```

inherited class:
- `CachableTextMessage: CachableMessage<void>`
- `CachableAssetMessage: CachableMessage<Asset>`

**Comment by chpapa** [comment]
@Steven-Chan @carmenlau 

I guess it would be helpful to illustrate the use cases for the offline cache, and how it might affect the API, before planning the spec of how the cache works.

I suppose we focus at the Conversation View of UIKit for now, thus the case will be:

## Standard Use Case

1. When I click on every Conversation, last n (say 5000?) messages should be cached offline
    1. Display last 50 messages, and load 50 more from cache as users scroll up.
    1. Able to search via offline cache first, (optionally) search online afterwards
1. When I press send a message, it will show up in the conversation list first, and send in the background, two result might happens: 
    1. Send succeed, show as normal message
    1. Send failure, show a error state for retry (retry could be just temp show it, a button, or the text goes to textbook again, different chat app have different behaviour)

## Change on Chat SDK

In that cases, I imagine we can provide the following way to do it:

Idea: Skygear SDK manage a message storage, which is sort of like a journal / ledger of what happen in a conversation (but not exactly, more below)

1. `getMessages(conversation, limit, beforeTime, order)` always return a cached respond immediately, and will call the real getMessages online later. The new messages from online, will be played back via `subscribe(handler)`.
1. `subscribe(handler)` always fire up for new messages arrives to the cache.

So users should always create a new Conversation View (using UIKit or not) by constructing message list by getMessages(), and listen to `subscribe()` callback at the same time for any new messages arrived, and render them in the correct order.

Since Skygear Chat don't have a ledger now, so if a messages was sent, than edit twice when the client is offline, the message will only arrive as a new message for the client, instead of "created" => "updated" => "updated". But I think it should be fine for most use cases. Unless we really want to provide a ledger. (Which is possible I think, we have message history right? But that requires much more loading on the DB.)

It is also possible for new messages arrive via `subscribe(handler)` earlier than the old messages sent between my last online and now. (i.e. the real `getMessages` return slower than a new message via pubsub), I think it is okay, as long as our offline store and the user's UI display message by timestamp in message, not by the order of their arrival (which we will need to show it in tutorial and sample code of docs)

**Comment by chpapa** [comment]
This 2nd message provide some other supplement thoughts for the 1st message.

## Boris have the same idea before

@akiroz , our 1 year interns wanted something like these when he did a chat project before:

```
var messages = new ManagedMessageList({
  initialFetch: 50,
  subscribeNewMessages: true,
  syncOnReconnect: true,
});

messages => []Message

messages.on('update', function() {});

messages.fetchOlder(20)
```

## Question on timing
The message store now rely on date time to order the message correctly. Shall we always trust server's time so message are ordered at the time they arrive the server?

## Expand the cache functionality to Sending Message

Most chat app don't have it, but if someone really want to build a chat app that will send a chat messages even in offline eventually, we should have a new method like `sendMessageEventually(conversation, body, metadata, asset)`, and provide callback for success. The eventually part is our SDK should try to store the message in local cache, and whenever there is chance we will try to clear up the local cache.

## Expand the cache functionality to Conversations List

I guess similarly the concept of the cached message above might be useful for conversation list.

**Comment by carmenlau** [comment]
In milestone 3, we will target to complete the message cache for conversation view in iOS and Android

**Comment by carmenlau** [comment]
Current status, iOS and Android SDK were updated and released. And we paused the development of chat SDK, i think we need review the issue priority again.
