### ISSUE TITLE
Improve the usability of Chat API

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#66]
# Description

This feature issue is to suggest immediate changes on Skygear Chat API:

1. Skygear Chat have two confusing concepts: `UserConversation` and `Conversation`; 
2. Can't subscribe to change of `UserConversation` objects (i.e. if you were added to a new conversation, you have no way to show it on conversation list UI except polling)
3. Complete remaining issues:
* edit / delete message: SkygearIO/chat#97 SkygearIO/chat#92
* backward incompatible change: SkygearIO/chat#94
* transient last_message (last_read_message?) by default in getConversations: SkygearIO/chat#96
* consider this API signature change: SkygearIO/chat-SDK-JS#52
* potentially related bug with pt2: SkygearIO/chat-SDK-JS#41
4. Update the demo apps with the new API changes on 1 and 2.

@rickmak can you look into these and see if it make sense to update Skygear Chat and the demo app for @royuen?

### 1. Proposal to merge `UserConversation` and `Conversation`
* Rename `UserConversation` to `Conversation` on SDK level.
* Flatten the attributes/methods of `UserConversation` and `Conversation`
* For all methods taking `Conversation` as attributes, they should take the *new* `Conversation` object now. 
* Remove `getUserConversation` and `getUserConversations`

@rickmak have a counter argument for keeping `UserConversation` and `Conversation`: developers can develop an admin portal which shows different users' unread count, however, I think it doesn't make sense. As most API in the Skygear Chat SDK doesn't really make senses once lost the context of "logged in users", e.g.:

* `createMessage` already assume the Message is created by currently logged in users.
* `getUnreadCount` and `getUnreadMessageCount` actually needs to assume it is returning the unread count of currently logged in users

So in short, unless we have some major changes to the current APIs, I don't see how keeping `Conversation` and `UserConversation` distinction in Skygear Chat would help developers to develop an admin portal. The API was just inconsistent here, not a matter of exposing underlying implementation or not. I would rather keep it simple and merge `UserConversation` into `Conversation` and just have one, simple conversation object representing the conversation object with parameters specific to the currently logged-in users.

For the admin portal use cases, I think that would be advanced use cases and we either have a very good guide on those admin portal cases in future, or they are expected to understand the inner of Skygear Chat to query the database directly and do that.
 
### 2. Provide the *new* `Conversation` object update in `subscribe` function

Thus we can return these parameters:

```
{
  "record_type": "conversation",
  "event_type": "create",
  "record": recordObj,
  "original_record": nulll
}
```

`event_type` should mean:
* `create`: when users is added to a conversation
* `delete`: when users was removed from a conversation
* `update`: when one of the `Conversation` and `UserConversation` table's attributes was updated if user participates in the conversation

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
@howawong @rickmak can you help update this feature issue to reflect the latest discussion of changes to Chat SDK

**Comment by howawong** [comment]
@chpapa  @rickmak
I think the outstanding issues are
1. skygeario/chat#97
2. skygeario/chat#31 and
3. updating demo apps.

**Comment by chpapa** [comment]
Closing the feature issue, remaining Guides update at SkygearIO/guides#96

**Comment by howawong** [comment]
After skygear-demo/react-chat-demo#65 is merged, this issue can be closed.

**Comment by howawong** [comment]
All tasks are finished. Closing this issue.
