### ISSUE TITLE
HTTP2 support for Client SDK

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#7]
# Description

Add support for HTTP2 and take advantages of the protocol. e.g. Reduce overhead of multiple connections.

# Related Issues

- Server Issues: skygeario/skygear-server#326
- Client Issues: skygeario/skygear-SDK-Android#113
- Guides Issues

# Design/Specification

WIP

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

**Comment by tensiuyan** [comment]
Supported multiplexing, the rest of HTTP2 features aren't supported.
