### ISSUE TITLE
Field ACL dashboard

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/features#84]
# Description

A Dashboard to read and modify Record Field ACL. refs: https://github.com/SkygearIO/features/pull/69

# Portal Design

TBD

## Portal Features

Configure per record field based ACL for each accessibility and discovery level.

- Tablar display on Row(User Roles) x Column(Accessibility and discovery level)
- Restore to default
- Batch updates
- Mark what is modified
- Batch save on commit

# API Design

https://github.com/SkygearIO/features/blob/master/features/48-user-profile-discovery/field-based-acl.md

## Scenario

**Put list of Scenario how developers will use this API**

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [x] Specification Design Approval
- [x] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
@carmenlau @Steven-Chan Default user's `email` and `username` still show as `Customize` ACL and not using `Discoverable`?

**Comment by chpapa** [comment]
Another minor issue spotted: Default Field ACL's default value just say `Default`, however, it should say `Public` instead. Default is default doesn't give any information.

**Comment by chpapa** [comment]
Closing it as the 1st version was already deployed on production.
