### ISSUE TITLE
Update Record with a Similar-To SQL's WHERE clause

### ISSUE THREAD

**Issue by howawong** [SkygearIO/features#86]
# Description

Support SQL-like Update Function on Records

# API Design

## Javascript
```javascript
const update = new skygear.Update(Delivery, {
        'delivery': 'Hong Kong'
    })
    .contains('_id', ['29f78402-4584-4495-acb6-ba5e9597165d',
        '6fbe29d7-b3d9-46cf-883b-f1f8e7063796'
    ]);
skygear.publicDB.update(update).then((numberOfRows) => {
    console.log(numberOfRows)
});
```

## Java
```java
Container skygear = Container.defaultContainer(this);
Database publicDB = skygear.getPublicDatabase();
HashMap<String, Object> updateMap = new HashMap<String, Object>();
updateMap["delivery"] = "Hong Kong";
Update deilveryUpdate = new Update("Delivery", updateMap).contains("_id", new String[] {
        "29f78402-4584-4495-acb6-ba5e9597165d",
        "6fbe29d7-b3d9-46cf-883b-f1f8e7063796"
});
publicDB.update(deilveryUpdate, new RecordUpdateResponseHandler() {
    @Override
    public void onQuerySuccess(int numberOfRows) {

    }

    @Override
    public void onQueryError(String reason) {

    }
});
```
Objective C
```objc
NSPredicate *inPredicate = [NSPredicate predicateWithFormat: @"%@ IN attribute", 
[NSArray arrayWithObjects:  @"29f78402-4584-4495-acb6-ba5e9597165d", @"6fbe29d7-b3d9-46cf-883b-f1f8e7063796", nil]];
SKYUpdate *update = [SKYUpdate queryWithRecordType:@"Delivery"
    fields:{@"delivery": @"Hong Kong"}
    predicate: inPredicate];
SKYDatabase *publicDB =  [[SKYContainer defaultContainer] publicCloudDatabase];

[publicDB performUpdate:update completionHandler:^(NSInteger numberOfRows, NSError *error) {
    if (error) {
        NSLog(@"error querying orders: %@", error);
        return;
    }
}];
```

## Scenario

Very common use case

# Open Questions

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Server Issues
- Client Issues
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
Duplicated / similar with #11
