### ISSUE TITLE
Support Postgres view / materialized view in Skygear Record API and Skygear Portal

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/features#87]
# Description

The goal of this feature is to allow developer to define more complicated query on server side to handle more advanced use cases AND to make this feature accessible for those who have no knowledge of Postgres view.

Kind of like https://github.com/SkygearIO/features/issues/10, but utilize Postgres view and materialized view.

This article explains view and materialized view pretty well:
https://www.compose.com/articles/its-a-view-its-a-table-no-its-a-materialized-view/

Discussed with @cheungpat, he briefly tested Postgres view with the current version of skygear-server, and it works seamlessly with the skygear query api (of course need further testing, like `transientInclude`). However, query api would be the only record api that supports Postgres view, so skygear-server need to return error properly if other api is touched with the view.

I would consider Postgres view a more advanced feature, and developer would need to touch the db directly to create a view. So it would be nice if skygear could provide API, public or private, to create a Postgres view. And my final target of this issue is to make portal support creating and managing the views, without writing a single line of code. I think it would be nice enough to become a WOW feature of the portal.

# API Design

- Handle Postgres view and materialized view as a kind of record type, so assuming there is a Postgres view named `RecordA`, when `RecordA` is defined as a record type in SDK:
  - `RecordA` record can be used to initialize a query object 
  - `RecordA` record object cannot be used in save api
  - `RecordA` record object cannot be used in delete api
- These Postgres view must fulfil the following requirement, otherwise skygear cannot handle properly:
  - contains all meta field, e.g. created_at, acl

# Portal Design

I think this would be the most important part to make this feature really shines.

First of all, there should be a page showing the schema of all current record type (I am not sure if this has been in any issue of the feature repo).

There would be a separate page(s) in the portal containing all view-related functions. User may create, update and delete views in this page(s).

### Create or update the view

View is actually just a sql query. So it would be the same task to allow user to build a sql query on the portal.

I do not have a full picture of how it should work on the portal yet. 

I imagine that the design would be based on the fact the skygear is managing the schema of the tables. There would be a list of tables and their columns. When user creates or updates a view, he will pick one of the table, select some (or all) columns, then he will pick another table, define the join condition by picking a column from the two joining tables. Unlike the skygear record API, this will have no limitation on the join depth.

**(I would really love this thing.)** User may make this view to be a materialized view by clicking a checkbox. And since skygear has the definition of the view, it can then create triggers to make the materialized view refresh properly when relevant tables are updated. The portal may even let the user to choose the refresh strategy, lazy or eager, based on the use case of the tables, if it a more frequently-read or frequently-write table.

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by tensiuyan** [comment]
Sounds like this solution will solve the Skygear record API limitations and enable Skygear to support complex use cases. LM.
