### ISSUE TITLE
SDK API reference doc hosting

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/features#88]
# Description

This issue aims to host SDK API reference in docs.skygear.io.

Proposed URL for SDK API reference:

```
https://docs.skygear.io/<library>/reference/<version>
```

Library can be one of the following:

* `js`
* `ios`
* `android`

Version can be one of the following:

* `latest` (point to the lastest released version)
* `v1` (point to the latest released version of the v1 branch)
* `v1.0.0`

# Related Issues

- Server Issues
- Client Issues
  - [ ] SkygearIO/skygear-SDK-JS#243
  - [ ] SkygearIO/skygear-SDK-iOS
  - [ ] SkygearIO/skygear-SDK-Android
- Guides Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
It looks like we're working on it already, so I put it on milestone 2 for tracking.

**Comment by carmenlau** [comment]
Both core and chat sdk api references are updated to host in docs.skygear.io.
