### ISSUE TITLE
Alias for Static Assets

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/features#90]
# Description
(for hosting on skygeario.com only)
Currently, static assets are having url like http://appid.skygeario.com/static/.
It would be better to have an alias/proxy, so the asset are at root level.
e.g. http://appid.skygearhosting.com/

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by david90** [comment]
Since we want to encourage people to host their static site at skygear.io, but the `/static/` route breaks many assumptions of frameworks (e.g. Polymer, React).

Suggestion:
APIs should go at `http://appid.skygeario.com/api/`, while static assets should be at `http://appid.skygeario.com/`

**Comment by seventhmoon** [comment]
or ... even something like subdomain 
API: https://appid.api.skygeario.com/
Static: https://appid.hosting.skygeario.com/

and one step forward, how to work with CDN provider in this case?

**Comment by chpapa** [comment]
#95 is duplicated with this feature issue. Since #95 already tracked the development. I'm closing this issue.
