### ISSUE TITLE
Custom domain to static asset

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/features#95]
# Description

Skygear.io is providing static hosting to developers. A common usage is hosting web single page application. In a single page application context we will have:

static: for html, js and css
skygear-server: as the backend datastore

Developers are currently deployed everything(both cloudcode and static asset) to skygeario.com and will have following URL as entry point

`https://appname.skygeario.com/static/index.html`

Which is fine for staging or internal development. But when the client needs to release their app. They will want the URL looks like `https://webapp.oursky.com/`.

# Portal Design

## Portal Features

- Instruction on how to set up CNAME
- Target domain name
- Upload the SSL cert for https

## Scenario

**Put list of Scenario how developers will use this API**

# Open Questions

- Naked domain will not be supported in phase 1.
- Restricting the asset to be on `public_html`?
- The domain name added here should also add to CORS / OAuth Domain Whitelist (#5)

**Put a list of open questions here before a complete design / specification is decided**

# Related Issues

- Cloud Issues
- Portal Issues

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by chpapa** [comment]
@carmenlau I have tried the custom domain to static asset feature in portal, and here are something I would suggest to change:

1. Under Configure Domain, change copywriting of "Domain not verified/configured" => "Domain not verified/configured, some DNS server may take hours for changes to be effective" oursky/skygear-portal#553
1. Under "Edit Domain" popup, change "Edit" button to "Confirm", and after clicking it the popup should go away. oursky/skygear-portal#550
1. Let's encrypt cert generation seems didn't works oursky/skygear-portal#554

**Comment by chpapa** [comment]
Moreover, may I confirm the following two features described in feature description was not completed? (We can open another feature issue for them)

* Upload the SSL cert for https
* The domain name added here should also add to CORS / OAuth Domain Whitelist (#5)

**Comment by carmenlau** [comment]
- Upload ssl cert is not supported and we are supporting let's encrypt certs
- The skygear server default CORS are "*" and SSO allowed redirect url is allow all by default. So no changes are needed.

I will close this issue as this feature are completed. Let's open another issue for improvement if needed! :)
