### ISSUE TITLE
Android Chat UIKit Conversation View

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/features#97]
# Description

Focus at implementing UIKit for Android, Conversation View

# Related Issues

* [All issues labeled with `area/uikit/Conversation`](https://github.com/SkygearIO/chat-SDK-Android/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fuikit%2FConversation)
* [All issues labeled with `milestone3` and `area/uikit/Conversation`](https://github.com/SkygearIO/chat-SDK-Android/issues?q=is%3Aopen+is%3Aissue+label%3Aarea%2Fuikit%2FConversation+label%3Aworkflow%2FMilestone3)

# Progress Tracker

- [ ] Specification Design Approval
- [ ] Write (code + tests + API docs) then get them merged. **Put All PR there**
  - [ ] Code
  - [ ] Minimal tests
  - [ ] Minimal API Docs
- [ ] Guides. **Put All PR there**
- [ ] Release
  - [ ] Update release notes
  - [ ] Release

# Advice

- Specification Design Approval
  - Once you get LGTM from another Skygear Core Team Member, you can check this checkbox. And apply the "workflow/design-complete" label.
- Coding
  - Use as many PRs as you need.  Write tests in the same or different PRs, as is convenient for you.
  - API doc should goes in the same PR with the code.
  - As each PR is merged, add a comment to this issue referencing the PRs.
  - When you are done with the code, apply the "workflow/code-complete" label.
- Guides
  - Write or modify guides and get them merged in https://github.com/skygeario/guides
  - When the PR of guides is merged, check this checkbox and apply the "workflow/guides-complete" label.

**Comment by carmenlau** [comment]
Initial schedule:

Milestone 2.0 (week 5-6)
- [UIKit] Initial setup SkygearIO/chat-SDK-Android#41
- [UIKit] Model setup SkygearIO/chat-SDK-Android#45 
- [UIKit] Conversation view SkygearIO/chat-SDK-Android#42 

Milestone 2.1 (week 1-2)
- [UIKit] User List View SkygearIO/chat-SDK-Android#44
- [UIKit] Conversation List View SkygearIO/chat-SDK-Android#43

Milestone 3 (week 1)
- [UIKit] Conversation details page SkygearIO/chat-SDK-Android#46

Milestone 3 (week 2)
- [Demo] Project setup SkygearIO/android-chat-uikit-demo#1
- [Demo] Settings SkygearIO/android-chat-uikit-demo#3
- [Demo] Login and signup page SkygearIO/android-chat-uikit-demo#4

Milestone 3 (week 3)
- Feedback and update guide
